import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {pageBridge} from '../src/page.js';
const fixture=`<!doctype html><meta charset="utf-8"><title>北森操作回归</title><style>[hidden]{display:none!important}.phoenix-select{min-height:30px;border:1px solid}.list-data-container,.area-data-container{max-height:160px;overflow:auto}.icon-container{display:inline-block;width:20px;height:20px;border:1px solid}.phoenix-calendar-date,.phoenix-calendar-month-panel-month,.phoenix-calendar-year-panel-year{display:block;padding:5px}.constant-main-selector-container,.area-selector-container,.phoenix-calendar{border:1px solid;padding:10px}</style>
<form><button type="button" id="save">保存</button><button type="button" id="globalconfirm">确定</button><button>提交</button><div id="fields"></div></form>
<script>
window.counts={save:0,submit:0,confirm:0,cancel:0,navigate:0,select:0};save.onclick=globalconfirm.onclick=()=>counts.save++;document.querySelector('form').onsubmit=e=>{e.preventDefault();counts.submit++};
function field(id,label,calendar=false){const item=document.createElement('div');item.className='form-item';item.innerHTML='<label class="form-item__text">'+label+'</label><div class="phoenix-select"><ul class="phoenix-select__content"><li><input></li></ul>'+(calendar?'<svg><use href="#prefix__a_field_date_time_picker"></use></svg>':'')+'</div>';fields.append(item);const el=item.querySelector('.phoenix-select');el.id=id;return el;}
function commit(el,value){el.querySelector('.phoenix-select__content').innerHTML='<li class="phoenix-select__tag">'+value+'</li>';}
function footer(root,cls,ok,cancel){const f=document.createElement('div');f.className=cls;root.append(f);for(const [label,fn]of [['取消',cancel],['确定',ok]]){const outer=document.createElement('div');outer.className='phoenix-button';outer.innerHTML='<div class="phoenix-button__wraper"><div class="phoenix-button__content">'+label+'</div></div>';outer.firstChild.onclick=fn;f.append(outer);}}
function simple(id,missing=false){const el=field(id,'单选'+id);el.onclick=()=>{const old=document.querySelector('[data-owner='+id+']');if(old){old.remove();return;}let selected='';const root=document.createElement('div');root.className='constant-main-selector-container';root.dataset.owner=id;root.innerHTML='<input placeholder="搜索"><div class="left-container"><div class="list-data-container"></div></div><div class="right-container"><span class="select-data-num">已选 0/1</span><div class="select-data-container"></div></div>';document.body.append(root);const render=q=>{const list=root.querySelector('.list-data-container');list.replaceChildren();for(const label of ['选项甲','选项乙','禁用项'].filter(x=>!q||x.includes(q))){const n=document.createElement('div');n.className='list-item-container';n.innerHTML='<span class="icon-container"><svg width="14" height="14"><circle cx="7" cy="7" r="6"></circle></svg></span><span class="item-text-label no-hover">'+label+'</span>';if(label==='禁用项')n.setAttribute('aria-disabled','true');n.querySelector('svg').onclick=()=>{if(label==='禁用项')return;counts.select++;selected=label;root.querySelector('.select-data-num').textContent='已选 1/1';root.querySelector('.select-data-container').textContent=label;};list.append(n);}};render('');root.querySelector('input').oninput=e=>setTimeout(()=>render(e.target.value),150);footer(root,'selector-footer-button',()=>{counts.confirm++;if(!missing)commit(el,selected);root.remove();},()=>{counts.cancel++;setTimeout(()=>root.remove(),120);});};}
simple('constant');simple('discard',true);
const area=field('area','地区');area.onclick=()=>{const old=document.querySelector('.area-selector-container');if(old){old.remove();return;}const root=document.createElement('div');root.className='area-selector-container';root.innerHTML='<div class="left-container"><div class="area-data-container"></div></div><div class="right-container">已选地区 <span class="count">0 /1</span><div class="selected"></div></div>';document.body.append(root);let selected='',path=[];function level(depth){const list=root.querySelector('.area-data-container');list.replaceChildren();const names=[['示例省','其他省'],['示例市'],['示例区']][depth];for(const name of names){const row=document.createElement('div');row.className='area-item-container';row.innerHTML='<span class="icon-container visible"><svg width="14" height="14"><circle cx="7" cy="7" r="6"></circle></svg></span><span class="area-text-label'+(depth===2?' no-hover':'')+'">'+name+'</span>';row.querySelector('svg').onclick=()=>{counts.select++;selected=name;root.querySelector('.count').textContent='1 /1';root.querySelector('.selected').textContent=name;};row.lastChild.onclick=()=>{if(depth===2)return;counts.navigate++;path.push(name);setTimeout(()=>level(depth+1),400);};list.append(row);}}level(0);footer(root,'area-footer-button',()=>{counts.confirm++;commit(area,selected);root.remove();},()=>{counts.cancel++;root.remove();});};
function calendar(id,type){const el=field(id,type==='date'?'完整日期':'开始月份',true);el.onclick=()=>{if(window.deferCalendar){window.deferCalendar=false;return;}const old=document.querySelector('[data-owner='+id+']');if(old){old.remove();return;}const root=document.createElement('div');root.className='phoenix-calendar';root.dataset.owner=id;document.body.append(root);let year=2026,month=9,decade=2020;function base(){root.replaceChildren();if(type==='date'){const input=document.createElement('input');input.className='phoenix-calendar-input';root.append(input);}const h=document.createElement('div');h.className='phoenix-calendar-header';h.innerHTML='<button type="button" class="phoenix-calendar-year-select">'+year+'年</button><button type="button" class="phoenix-calendar-month-select">'+month+'月</button>';root.append(h);h.firstChild.onclick=()=>{if(type==='month')throw Error('Must use nested month panel year switch');years();};h.lastChild.onclick=months;}
function years(){base();const p=document.createElement('div');p.className='phoenix-calendar-year-panel';p.innerHTML='<button type="button" class="phoenix-calendar-year-panel-prev-decade-btn">前十年</button><button type="button" class="phoenix-calendar-year-panel-next-decade-btn">后十年</button>';root.append(p);p.firstChild.onclick=()=>{counts.navigate++;decade-=10;years();};p.children[1].onclick=()=>{counts.navigate++;decade+=10;years();};for(let y=decade;y<decade+10;y++){const a=document.createElement('a');a.className='phoenix-calendar-year-panel-year';a.textContent=y;a.onclick=()=>{counts.navigate++;year=y;type==='month'?months():days();};p.append(a);}}
function months(){base();const p=document.createElement('div');p.className='phoenix-calendar-month-panel';p.innerHTML='<button type="button" class="phoenix-calendar-month-panel-year-select">'+year+'</button>';root.append(p);p.firstChild.onclick=years;for(let m=1;m<=12;m++){const a=document.createElement('a');a.className='phoenix-calendar-month-panel-month';a.textContent=m+'月';a.onclick=()=>{counts.navigate++;month=m;if(type==='month'){counts.select++;commit(el,year+'/'+String(month).padStart(2,'0'));root.remove();}else days();};p.append(a);}}
function days(){base();const table=document.createElement('table');root.append(table);for(let d=1;d<=31;d++){const cell=document.createElement('td');cell.className='phoenix-calendar-cell';cell.innerHTML='<div class="phoenix-calendar-date">'+d+'</div>';if(d===31)cell.setAttribute('aria-disabled','true');cell.firstChild.onclick=()=>{if(d===31)return;counts.select++;commit(el,year+'-'+String(month).padStart(2,'0')+'-'+String(d).padStart(2,'0'));root.remove();};table.append(cell);}const adjacent=document.createElement('td');adjacent.className='phoenix-calendar-cell phoenix-calendar-last-month-cell';adjacent.innerHTML='<div class="phoenix-calendar-date">3</div>';adjacent.onclick=()=>{throw Error('Clicked adjacent month')};table.append(adjacent);}
type==='month'?months():days();};}
calendar('month','month');calendar('date','date');
</script>`;
const browser=await chromium.launch({headless:true,channel:'chromium'});
try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent(fixture);
 const scan=await page.evaluate(pageBridge,{action:'scan',token:'beisen'});assert.equal(scan.fields.length,5);assert(scan.fields.every(f=>f.supported),JSON.stringify(scan.fields));assert.equal(scan.fields.find(f=>f.label==='开始月份').type,'month');assert.equal(scan.fields.find(f=>f.label==='完整日期').type,'date');assert.equal(await page.locator('.constant-main-selector-container,.area-selector-container,.phoenix-calendar').count(),0);assert.equal(await page.evaluate(()=>counts.select+counts.confirm),0);
 async function fill(label,value,expected=true,overwrite=false){const item={id:scan.fields.find(f=>f.label===label).id,value};const r=await page.evaluate(pageBridge,{action:'fill',token:'beisen',items:[item],overwrite});assert.equal(r.results[0].ok,expected,JSON.stringify(r));if(expected){const v=await page.evaluate(pageBridge,{action:'verify',token:'beisen',items:[item]});assert(v.results[0].ok,JSON.stringify(v));}return r.results[0];}
 await fill('单选constant','选项乙');assert.equal(await page.locator('#constant .phoenix-select__tag').textContent(),'选项乙');assert.match((await fill('单选constant','缺失选项',false,true)).reason,/SELECT_NO_MATCH/);assert.equal(await page.locator('#constant .phoenix-select__tag').textContent(),'选项乙');
 await fill('地区','示例省示例市示例区');assert.equal(await page.locator('#area .phoenix-select__tag').textContent(),'示例区');await page.evaluate(()=>window.deferCalendar=true);await fill('开始月份','2024-09');await fill('完整日期','1998-12-03');
 assert.match((await fill('完整日期','2000-02',false,true)).reason,/DATE_FORMAT/);assert.match((await fill('完整日期','2001-02-29',false,true)).reason,/DATE_FORMAT/);assert.match((await fill('完整日期','2000-12-31',false,true)).reason,/DATE_DISABLED/);assert.equal(await page.locator('#date .phoenix-select__tag').textContent(),'1998-12-03');
 assert.match((await fill('单选discard','选项甲',false)).reason,/SELECT_NOT_COMMITTED/);
 await page.evaluate(()=>document.querySelector('#month').onclick=()=>{});assert.match((await fill('开始月份','2020-01',false,true)).reason,/SELECT_POPUP/);assert.equal(await page.locator('.constant-main-selector-container,.area-selector-container,.phoenix-calendar').count(),0);const counts=await page.evaluate(()=>window.counts);assert.equal(counts.save+counts.submit,0);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'PASS',checks:['read-only scan cancels popups','click inner button handler and confirm','selection alone does not count as fill','region navigation then radio selection then confirmation','leaf display receipt after exact path','date and month precision','year decade navigation','disabled/invalid/incomplete date rejected','failed search preserves existing value','discarded result fails readback','no save or submit'],counts}));
}finally{await browser.close();}
