import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {mkdtemp,cp,readFile,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html=`<!doctype html><html><head><meta charset="utf-8"><title>演示公司 · 校招网申</title><style>body{font:16px system-ui;max-width:780px;margin:40px auto}fieldset{margin:20px 0;padding:24px;border:1px solid #ccd}label{display:block;margin:12px 0}input,select{padding:8px}h1{color:#087f6c}</style></head><body><h1>演示公司 · 校招网申</h1><form id="application"><fieldset><legend>基本信息</legend><label>姓名<input name="candidate_name" required></label><label>电子信箱<input type="email" name="mail" required></label><label>手机号<input name="phone" value="13900000000"></label><label>出生日期<input name="birthday" type="date"></label><label>简历附件<input name="resume" type="file"></label><label>自制下拉<input role="combobox" name="custom_combo" readonly></label><input type="hidden" name="csrf" value="token"><label><input name="consent" type="checkbox">我同意隐私条款</label></fieldset><fieldset><legend>性别</legend><label><input type="radio" name="gender" value="M">Male</label><label><input type="radio" name="gender" value="F">Female</label></fieldset><fieldset><legend>教育经历 1</legend><label>学校<input name="school"></label><label>Degree attained<select name="degree"><option value="">请选择</option><option value="b">Bachelor</option><option value="m">Master</option></select></label><label>入学时间<input name="start" type="month"></label></fieldset><button type="submit">提交申请</button></form><script>window.events=[];document.addEventListener('input',e=>events.push(['input',e.target.name,e.target.value]));document.addEventListener('change',e=>events.push(['change',e.target.name,e.target.value]));window.submissions=0;document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();submissions++});</script></body></html>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(req.url==='/embedded'?'<label>现居城市<input name=iframeCity></label>':html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'jev-apply-test-'));const extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});
// Only this temporary test copy gets localhost permission, replacing a toolbar activeTab grant.
const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));
let ctx;const errors=[];const calls=[];
const launch=()=>chromium.launchPersistentContext(path.join(root,'profile'),{headless:true,channel:process.env.BROWSER_CHANNEL||'chromium',args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],viewport:{width:1100,height:900}});
try{
 ctx=await launch();
 ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 ctx.on('request',req=>{if(req.url()==='https://api.typesafe.ai/v1/systemone'&&req.method()==='POST')calls.push(req.postDataJSON());});
 if(!process.env.TYPESAFE_API_KEY)await ctx.route('https://api.typesafe.ai/v1/systemone',async route=>{
  const body=route.request().postDataJSON();const answers={};
  for(const [qname,q]of Object.entries(body.questions)){
   const i=Number(qname.slice(1));let choice='none';
   if(body.state.fields){const f=body.state.fields[i];choice=f.label==='电子信箱'?'base.email':f.label==='Degree attained'?'education.0.degree':'none';}
   else{const item=body.state.items[i];choice=item.profileValue==='男'?'o0':item.profileValue==='本科'?'o1':'none';}
   answers[qname]={type:'choice',choice,confidence:.99,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===choice?1:0]))};
  }
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({model:'jev-1.13.0',answers,usage:{input_tokens:200,output_tokens:30}})});
 });
 let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker',{timeout:20000});const id=new URL(worker.url()).host;
 const options=await ctx.newPage();await options.goto(`chrome-extension://${id}/options.html`);await options.getByRole('heading',{name:'整理一次，反复使用。'}).waitFor();
 // Generate a one-page text PDF to exercise local worker extraction without external tools.
 const stream='BT /F1 12 Tf 50 740 Td (Demo Candidate) Tj 0 -20 Td (demo@example.test) Tj 0 -20 Td (13812345678) Tj ET';
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];
 let pdf='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
 await options.locator('#pdf-file').setInputFiles({name:'demo-resume.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdf)});await options.locator('#status').filter({hasText:'已本地读取 1 页'}).waitFor({timeout:15000});
 assert.equal(await options.locator('[data-key=email]').inputValue(),'demo@example.test');assert.equal(await options.locator('[data-key=phone]').inputValue(),'13812345678');
 await options.locator('[data-key=fullName]').fill('演示候选人');await options.locator('[data-key=gender]').fill('男');await options.locator('[data-key=birthday]').fill('2000-02-03');await options.locator('#add-education').click();await options.locator('[data-key=school]').fill('示例大学');await options.locator('[data-key=degree]').fill('本科');await options.locator('[data-key=start]').fill('2018-09');await options.locator('#notes').fill('PRIVATE-NOTES: 周五以后可以面试，证书待补充。');await options.locator('#save').click();await options.locator('#status').filter({hasText:'已保存到当前浏览器'}).waitFor();
 const stored=await worker.evaluate(()=>chrome.storage.local.get('profile'));assert.equal(stored.profile.base.fullName,'演示候选人');assert(!JSON.stringify(stored).includes('Demo Candidate'));
 await worker.evaluate(key=>chrome.storage.session.set({apiKey:key}),process.env.TYPESAFE_API_KEY||'apikey_fixture_not_real');
 const target=await ctx.newPage();await target.goto(origin);const tabs=await worker.evaluate(()=>chrome.tabs.query({}));const targetTab=tabs.find(t=>t.url?.startsWith('http://127.0.0.1'));assert(targetTab);
 const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#profile-info').filter({hasText:'已保存'}).waitFor();
 // The sidebar is loaded as an extension page; make the fixture the active tab before scanning.
 await target.bringToFront();await panel.locator('#scan').click();await panel.locator('#status').filter({hasText:'扫描完成'}).waitFor();
 assert.equal(await panel.locator('.field-title').filter({hasText:'我同意'}).count(),0);assert.equal(await panel.locator('.field-title').filter({hasText:'csrf'}).count(),0);
 assert(await panel.locator('#fields').innerText().then(t=>t.includes('附件需要手动上传')));
 await panel.locator('#match').click();await panel.locator('#status').filter({hasText:'匹配完成'}).waitFor({timeout:120000});
 const pending=await panel.locator('#count').innerText();assert(pending.startsWith('7 /'),`Expected 7 checked fields, got ${pending}`);
 await mkdir('test-artifacts',{recursive:true});await panel.setViewportSize({width:440,height:1000});await panel.screenshot({path:'test-artifacts/panel.png',fullPage:true});
 await target.bringToFront();await panel.locator('#fill').click();await panel.locator('#status').filter({hasText:'已填入 7 项'}).waitFor();
 assert.equal(await target.locator('[name=candidate_name]').inputValue(),'演示候选人');assert.equal(await target.locator('[name=mail]').inputValue(),'demo@example.test');assert.equal(await target.locator('[name=phone]').inputValue(),'13900000000');assert.equal(await target.locator('[name=birthday]').inputValue(),'2000-02-03');assert.equal(await target.locator('[name=degree]').inputValue(),'b');assert.equal(await target.locator('[name=start]').inputValue(),'2018-09');assert(await target.locator('[name=gender][value=M]').isChecked());assert(!(await target.locator('[name=consent]').isChecked()));assert.equal(await target.evaluate(()=>submissions),0);assert.equal(await target.locator('[name=resume]').inputValue(),'');assert((await target.evaluate(()=>events)).some(x=>x[0]==='input'&&x[1]==='candidate_name'));
 // Verify exact replay never silently overwrites data entered after a scan.
 const scan=await panel.evaluate(tabId=>chrome.runtime.sendMessage({action:'scan',tabId}),targetTab.id);const f=scan.fields.find(f=>f.name==='candidate_name');await target.locator('[name=candidate_name]').fill('用户稍后输入');
 const noOverwrite=await panel.evaluate(({tabId,token,f})=>chrome.runtime.sendMessage({action:'fill',tabId,token,items:[{...f,value:'SHOULD NOT WRITE'}],overwrite:false}),{tabId:targetTab.id,token:scan.token,f});assert.equal(noOverwrite.results[0].ok,false);assert.equal(await target.locator('[name=candidate_name]').inputValue(),'用户稍后输入');
 const dateField=scan.fields.find(x=>x.name==='birthday');
 const invalidDate=await panel.evaluate(({tabId,token,f})=>chrome.runtime.sendMessage({action:'fill',tabId,token,items:[{...f,value:'2024-13-40'}],overwrite:true}),{tabId:targetTab.id,token:scan.token,f:dateField});assert.equal(invalidDate.results[0].ok,false);assert.equal(await target.locator('[name=birthday]').inputValue(),'2000-02-03');
 await target.evaluate(()=>history.pushState({},'', '/next-step'));
 const stale=await panel.evaluate(({tabId,token,f})=>chrome.runtime.sendMessage({action:'fill',tabId,token,items:[{...f,value:'SHOULD NOT WRITE'}],overwrite:true}),{tabId:targetTab.id,token:scan.token,f});assert.equal(stale.results[0].ok,false);assert.equal(stale.results[0].reason,'页面已变化，请重新扫描');
 await target.evaluate(()=>{const f=document.createElement('iframe');f.src='/embedded';f.id='embedded';document.body.append(f)});await target.frameLocator('#embedded').locator('input').waitFor();
 const frameScan=await panel.evaluate(tabId=>chrome.runtime.sendMessage({action:'scan',tabId}),targetTab.id);const nested=frameScan.fields.find(x=>x.name==='iframeCity');assert(nested?.frameId>0);const frameFill=await panel.evaluate(({tabId,token,f})=>chrome.runtime.sendMessage({action:'fill',tabId,token,items:[{...f,value:'上海'}],overwrite:false}),{tabId:targetTab.id,token:frameScan.token,f:nested});assert(frameFill.results[0].ok);assert.equal(await target.frameLocator('#embedded').locator('input').inputValue(),'上海');
 if(!process.env.TYPESAFE_API_KEY){const mapping=calls.filter(x=>x.state.fields);assert(mapping.length>0);for(const call of mapping){assert(!JSON.stringify(call).includes('演示候选人'));assert(!JSON.stringify(call).includes('demo@example.test'));assert(!JSON.stringify(call).includes('PRIVATE-NOTES'));}assert(calls.some(x=>x.state.items));}
 await options.screenshot({path:'test-artifacts/profile.png',fullPage:true});await target.screenshot({path:'test-artifacts/filled.png',fullPage:true});
 const usageText=await panel.locator('#usage').innerText();
 // Close the entire browser process, then reopen the same profile and extension path.
 await ctx.close();ctx=await launch();ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 let [restartedWorker]=ctx.serviceWorkers();if(!restartedWorker)restartedWorker=await ctx.waitForEvent('serviceworker',{timeout:20000});assert.equal(new URL(restartedWorker.url()).host,id);
 const restored=await ctx.newPage();await restored.goto(`chrome-extension://${id}/options.html`);await restored.locator('#pdf-info').filter({hasText:'demo-resume.pdf'}).waitFor();
 assert.equal(await restored.locator('[data-key=fullName]').inputValue(),'演示候选人');assert.equal(await restored.locator('#notes').inputValue(),'PRIVATE-NOTES: 周五以后可以面试，证书待补充。');assert((await restored.locator('#pdf-text').textContent()).includes('Demo Candidate'));
 const keyPersisted=await restartedWorker.evaluate(async expected=>(await chrome.storage.local.get('apiKey')).apiKey===expected,process.env.TYPESAFE_API_KEY||'apikey_fixture_not_real');assert(keyPersisted);assert.deepEqual(await restartedWorker.evaluate(()=>chrome.storage.session.get('apiKey')),{});
 const downloaded=restored.waitForEvent('download');await restored.locator('#download-pdf').click();const pdfDownload=await downloaded;assert.equal(pdfDownload.suggestedFilename(),'demo-resume.pdf');assert.deepEqual(await readFile(await pdfDownload.path()),Buffer.from(pdf));
 const exported=restored.waitForEvent('download');await restored.locator('#export').click();const exportedData=JSON.parse(await readFile(await(await exported).path(),'utf8'));assert.equal(exportedData.notes,'PRIVATE-NOTES: 周五以后可以面试，证书待补充。');assert(!('apiKey'in exportedData));
 await restored.locator('#replace-file').setInputFiles({name:'replacement.pdf',mimeType:'application/pdf',buffer:Buffer.from(pdf)});await restored.locator('#status').filter({hasText:'已本地读取 1 页'}).waitFor();await restored.reload();await restored.locator('#pdf-info').filter({hasText:'replacement.pdf'}).waitFor();
 restored.once('dialog',d=>d.accept());await restored.locator('#delete-pdf').click();await restored.locator('#status').filter({hasText:'已删除选中的素材'}).waitFor();await restored.reload();assert(await restored.locator('#saved-pdf').isHidden());assert.equal(await restored.locator('#notes').inputValue(),'PRIVATE-NOTES: 周五以后可以面试，证书待补充。');
 const restoredPanel=await ctx.newPage();await restoredPanel.goto(`chrome-extension://${id}/panel.html`);await restoredPanel.locator('#key-info').filter({hasText:'已持久保存'}).waitFor({state:'attached'});await restoredPanel.locator('summary').filter({hasText:'设置当前服务的 API key'}).click();await restoredPanel.locator('#clear-key').click();await restoredPanel.locator('#key-info').filter({hasText:'未设置'}).waitFor();assert.deepEqual(await restartedWorker.evaluate(()=>chrome.storage.local.get('apiKey')),{});
 await restoredPanel.locator('#api-key').fill('apikey_new_local_fixture');await restoredPanel.locator('#save-key').click();await restoredPanel.locator('#key-info').filter({hasText:'已持久保存'}).waitFor({state:'attached'});await restoredPanel.reload();await restoredPanel.locator('#key-info').filter({hasText:'已持久保存'}).waitFor({state:'attached'});assert(await restartedWorker.evaluate(async()=>(await chrome.storage.local.get('apiKey')).apiKey==='apikey_new_local_fixture'));
 restored.once('dialog',d=>d.accept());await restored.locator('#clear').click();await restored.locator('#status').filter({hasText:'已清除个人资料、备注和全部素材'}).waitFor();await restored.reload();assert.equal(await restored.locator('#notes').inputValue(),'');assert.equal(await restored.locator('[data-key=fullName]').inputValue(),'');assert(await restartedWorker.evaluate(async()=>(await chrome.storage.local.get('apiKey')).apiKey==='apikey_new_local_fixture'));
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',browser:process.env.BROWSER_CHANNEL||'chromium',mode:process.env.TYPESAFE_API_KEY?'live Jev API with synthetic data':'mocked Jev API',checks:['MV3 service worker','local PDF extraction','profile save','field scan','Jev mapping','semantic option selection','preview','7 fills','input events','skip existing','no consent/file/submit','stale-page rejection','invalid date rollback','same-origin iframe','browser restart persistence','legacy session-key migration','original PDF byte-for-byte recovery','PDF replacement and deletion','notes export','key replacement and deletion','no browser page errors'],apiCalls:calls.length,usage:usageText}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
