import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html=`<!doctype html><meta charset="utf-8"><title>缓存回归</title><form><label>研究方向<input name="research"></label><label>培养方式<select name="study"><option value="">请选择</option><option value="full">全日制</option></select></label><button>保存</button></form><script>window.submits=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};</script>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'resume-cache-')),extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));let ctx,calls=0;const modelFields=[];
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
 await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_cache_fixture',deepseekApiKey:'sk-cache-fixture',profile:{base:{},notes:'研究方向：机器学习\n培养方式：全日制',education:[],work:[],custom:[]}}));
 await ctx.route('https://api.typesafe.ai/**',async route=>{calls++;const p=route.request().postDataJSON(),answers={};assert.equal(p.state.stage,'route');p.state.fields.forEach((f,i)=>{const choice=p.state.ranges[0].id;answers['q'+i]={type:'choice',choice,confidence:.99,probabilities:{[choice]:.99}}});await route.fulfill({json:{answers}});});
 await ctx.route('https://api.deepseek.com/**',async route=>{calls++;const p=JSON.parse(route.request().postDataJSON().messages.at(-1).content);modelFields.push(p.fields.map(f=>f.name));const fills=p.fields.map(f=>({fieldId:f.id,rangeId:p.assignments.find(x=>x.fieldId===f.id).range.id,quote:f.name==='research'?'机器学习':'全日制',value:f.name==='research'?'机器学习':f.options.find(o=>o.label==='全日制').value}));await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills})}}]}});});
 const target=await ctx.newPage();await target.goto(origin+'/resume');const panel=await ctx.newPage();/* Legacy preserve-existing mode remains available. */await panel.addInitScript(()=>addEventListener('DOMContentLoaded',()=>{document.querySelector('#review-existing').checked=false;}));await panel.goto(`chrome-extension://${id}/panel.html`);
 async function run(){await panel.locator('#team-keys').filter({hasText:'DeepSeek：已配置'}).waitFor();await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 2 项'}).waitFor({timeout:30000});assert.equal(await target.evaluate(()=>submits),0);}
 await run();const firstCalls=calls;assert(firstCalls>0);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('executedPlanCache'))).executedPlanCache.length,2);
 // Reload both surfaces and change DOM runtime IDs without changing the field semantics.
 await target.reload();await target.evaluate(()=>{const n=document.createElement('input');n.setAttribute('aria-label','页面新增字段');n.disabled=true;document.querySelector('form').prepend(n);});await panel.reload();await run();assert.equal(calls,firstCalls);assert.match(await panel.locator('#status').innerText(),/复用上次方案 2 项/);assert.equal(await panel.locator('.needs-confirmation').count(),2);assert.equal(await target.locator('[name=research]').inputValue(),'机器学习');
 assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts,undefined);
 // One changed selector invalidates just that field; the unchanged text field stays cached.
 await target.reload();await target.locator('[name=study] option').last().evaluate(e=>e.value='full-new');await panel.reload();await run();assert(calls>firstCalls);assert.deepEqual(modelFields.at(-1),['study']);assert.equal(await target.locator('[name=study]').inputValue(),'full-new');assert.match(await panel.locator('#status').innerText(),/复用上次方案 1 项/);
 // Clearing all personal material also clears this local cache.
 const oldRows=(await worker.evaluate(()=>chrome.storage.local.get('executedPlanCache'))).executedPlanCache;
 const options=await ctx.newPage();await options.goto(`chrome-extension://${id}/options.html`);options.on('dialog',d=>d.accept());await options.locator('#clear').click();await options.locator('#status').filter({hasText:'已清除个人资料'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('executedPlanCache'))).executedPlanCache,undefined);
 const stale=await options.evaluate(rows=>chrome.runtime.sendMessage({action:'cache-plans',rows,epoch:0}),oldRows);assert.equal(stale.ok,false);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('executedPlanCache'))).executedPlanCache,undefined);
 console.log(JSON.stringify({result:'PASS',firstRunModelCalls:firstCalls,secondRunModelCalls:0,checks:['persistent cache after panel/page reload','runtime ID rebinding','only changed option field reanalysed','cached predictions remain orange and are not learned facts','clear removes cached original text and rejects late writes','no website save or submit']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
