import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {mkdtemp,cp,readFile,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>示例科技 · 前端工程师申请</title><body><h1>前端工程师</h1><h2>欢迎有 React 项目经验的申请人</h2><form><label>姓名<input name="name"></label><label>个人介绍<textarea name="about" maxlength="150"></textarea></label><label>实习公司<input name="intern"></label><label>期望薪资<input name="salary"></label><label>城市<input name="city"></label><label>手机号<input name="phone" value="13900000000"></label><label>简历附件<input name="file" type="file"></label><label><input type="checkbox" name="consent">同意条款</label><button type="submit">提交</button></form><script>window.submitted=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submitted++};document.querySelector('[name=name]').addEventListener('change',e=>{e.target.readOnly=true});document.querySelector('[name=city]').addEventListener('change',e=>setTimeout(()=>{e.target.value=''},0));</script></body></html>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'resume-fill-team-'));const extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));
let ctx,mode='normal',draftSeen=false;const log=[],errors=[];
const intro='我通过 React 项目积累了前端开发与团队协作实践，希望将这些经验用于应聘岗位。';
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{headless:true,channel:process.env.BROWSER_CHANNEL||'chromium',args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],viewport:{width:1100,height:1000}});ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 await ctx.route('https://api.deepseek.com/chat/completions',async route=>{
  assert.equal(route.request().headers().authorization,'Bearer sk-team-fixture');const body=route.request().postDataJSON();const input=JSON.parse(body.messages.at(-1).content);assert(body.messages.some(m=>m.content.includes('Another model independently audits')));assert(input.pageContext.headings.includes('前端工程师'));assert(!input.fields.some(f=>f.name==='phone'));
  log.push({model:'deepseek',fields:input.fields.map(f=>f.name),repair:input.revisionFeedback.length>0,feedback:input.revisionFeedback});draftSeen=true;if(mode==='cancel')await new Promise(r=>setTimeout(r,800));
  const notes=input.sources.find(s=>s.id==='notes'),name=input.sources.find(s=>s.id==='base.fullName');const repair=input.revisionFeedback.length>0;
  const values={name:['陈晓','陈晓',name.id],about:[repair?intro:'精通 React，效率提升 50%','使用 React 完成前端项目，与团队沟通需求。',notes.id],intern:[repair?'旧公司':'新公司','在旧公司实习，随后在新公司全职工作。',notes.id],city:['上海','现居上海。',notes.id]};
  const fills=input.fields.flatMap(f=>values[f.name]?[{fieldId:f.id,value:values[f.name][0],evidence:[{sourceId:values[f.name][2],quote:values[f.name][1]}],reason:repair?'根据校核意见修正，保留真实经历并调整表达':'根据资料拟定'}]:[]);
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({model:'deepseek-flash',choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills})}}],usage:{prompt_tokens:700,completion_tokens:240}})});
 });
 await ctx.route('https://api.typesafe.ai/v1/systemone',async route=>{
  assert.equal(route.request().headers().authorization,'Bearer apikey_team_fixture');const payload=route.request().postDataJSON();assert(payload.state.items);assert(payload.state.sourcePortion.some(s=>s.id==='notes'));assert(Object.keys(payload.questions).length<=8);log.push({model:'jev',items:payload.state.items.map(i=>({label:i.field.label,value:i.proposedValue}))});
  if(mode==='review-down'){await route.fulfill({status:503,body:'{}'});return;}
  const answers={};payload.state.items.forEach((item,i)=>{const policy=item.field.label==='个人介绍'?'expression':'fact';answers[`q${i}_policy`]={type:'choice',choice:policy,confidence:.99,probabilities:{fact:policy==='fact'?1:0,expression:policy==='expression'?1:0,unclear:0}};for(const key of ['fit','unsupported','conflict'])answers[`q${i}_${key}`]={type:'noul',noul:key==='fit'?.99:.01};if(item.field.label==='实习公司'&&item.proposedValue==='新公司')answers[`q${i}_fit`].noul=.1;if(item.proposedValue.includes('50%'))answers[`q${i}_unsupported`].noul=.8;});
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({model:'jev-1.13.0',answers,usage:{input_tokens:650,output_tokens:100}})});
 });
 let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker',{timeout:20000});const id=new URL(worker.url()).host;
 await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_team_fixture',profile:{base:{fullName:'陈晓'},education:[],work:[],custom:[],notes:'使用 React 完成前端项目，与团队沟通需求。\n在旧公司实习，随后在新公司全职工作。\n现居上海。'}}));
 const target=await ctx.newPage();await target.goto(origin);const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#profile-info').filter({hasText:'已保存'}).waitFor();
 await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'一键协作需要两套密钥'}).waitFor();assert.equal(log.length,0);assert.equal(await target.locator('[name=name]').inputValue(),'');
 await worker.evaluate(()=>chrome.storage.local.set({deepseekApiKey:'sk-team-fixture'}));await panel.reload();await panel.locator('#team-keys').filter({hasText:'DeepSeek：已配置 · Jev：已配置'}).waitFor();
 await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 3 项，待人工核对 1 项，填写失败 1 项，跳过 2 项'}).waitFor({timeout:30000});
 assert.equal(await target.locator('[name=name]').inputValue(),'陈晓');assert.equal(await target.locator('[name=about]').inputValue(),intro);assert.equal(await target.locator('[name=intern]').inputValue(),'旧公司');assert.equal(await target.locator('[name=salary]').inputValue(),'');assert.equal(await target.locator('[name=city]').inputValue(),'');assert.equal(await target.locator('[name=phone]').inputValue(),'13900000000');assert.equal(await target.locator('[name=file]').inputValue(),'');assert(!(await target.locator('[name=consent]').isChecked()));assert.equal(await target.evaluate(()=>submitted),0);
 assert.deepEqual(log.map(x=>x.model),['deepseek','jev','jev','deepseek','jev']);const repair=log.find(x=>x.model==='deepseek'&&x.repair);assert.deepEqual(repair.fields,['about','intern','salary']);assert(repair.feedback.find(x=>x.fieldId).problems.length>0);assert((await panel.locator('#fields').innerText()).includes('已修正复核'));assert((await panel.locator('#fields').innerText()).includes('网页未保留预期值'));
 await mkdir('test-artifacts',{recursive:true});await panel.setViewportSize({width:460,height:1000});await panel.screenshot({path:'test-artifacts/collaboration-panel.png',fullPage:true});
 await panel.getByLabel('个人介绍 待填内容',{exact:true}).fill('我手动修改的介绍');await panel.getByLabel('个人介绍 待填内容',{exact:true}).blur();assert((await panel.locator('#fields').innerText()).includes('当前值尚未经过双 AI 校核'));
 // Stop during an in-flight draft: no reviewer call or field write is started.
 mode='cancel';draftSeen=false;await target.reload();const before=log.length;await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'DeepSeek 正在理解'}).waitFor();await panel.locator('#stop-collaboration').click();await panel.locator('#status').filter({hasText:'协作已停止'}).waitFor();assert.equal(log.slice(before).filter(x=>x.model==='jev').length,0);assert.equal(await target.locator('[name=name]').inputValue(),'');
 // Reviewer errors do not cause direct unreviewed DeepSeek filling.
 mode='review-down';await target.reload();await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'HTTP 503'}).waitFor();assert.equal(await target.locator('[name=name]').inputValue(),'');assert.equal(await target.locator('[name=about]').inputValue(),'');assert.equal(await target.evaluate(()=>submitted),0);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',browser:process.env.BROWSER_CHANNEL||'chromium',mode:'mocked dual AI',checks:['one click scans/drafts/audits/repairs/re-audits/fills','both credentials required and isolated','only failed fields repaired','grounded flexible wording accepted','missing salary held','wrong record repaired','invented metric rejected','readback handles read-only accepted fields and detects discarded values','existing values preserved','no submit/consent/upload','cancellation before writes','reviewer outage fails closed']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
