import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {mkdtemp,cp,readFile,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const form=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>DeepSeek 网申测试</title><body><form><label>候选人姓名<input name="full_name"></label><label>意向城市<input name="city"></label><label>最高教育资格<select name="degree"><option value="">请选择</option><option value="b">Bachelor</option><option disabled value="m">Master</option></select></label><label>意向岗位<textarea name="job"></textarea></label><label>联系方式<input name="phone" value="13900000000"></label><label>生日<input name="birthday" type="date"></label><label><input name="consent" type="checkbox">同意条款</label><button type="submit">提交</button></form><script>window.submitted=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submitted++}</script></body></html>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(form)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'resume-fill-deepseek-'));const extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));
const launch=()=>chromium.launchPersistentContext(path.join(root,'browser'),{headless:true,channel:process.env.BROWSER_CHANNEL||'chromium',args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],viewport:{width:1100,height:900}});
let ctx,mode='normal';const errors=[],requests=[];
try{
 ctx=await launch();ctx.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 await ctx.route('https://api.deepseek.com/chat/completions',async route=>{
  assert.equal(route.request().headers().authorization,'Bearer sk-fixture-deepseek');const body=route.request().postDataJSON();requests.push(body);assert.equal(body.model,'deepseek-flash');assert.equal(body.response_format.type,'json_object');
  if(mode==='unauthorized'){await route.fulfill({status:401,body:'{}'});return;}
  if(mode==='malformed'){await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({choices:[{finish_reason:'stop',message:{content:'not json'}}]})});return;}
  const input=JSON.parse(body.messages[1].content);assert(!JSON.stringify(input).includes('DO-NOT-SEND'));assert(!JSON.stringify(input).includes('RAW-PDF-BYTES'));
  const resume=input.sources.find(s=>s.label==='resume.txt');const notes=input.sources.find(s=>s.id==='notes');assert(resume&&notes);
  const answers={full_name:['陈晓','姓名：陈晓',resume.id],city:['上海','城市：上海',resume.id],degree:['b','学历：本科',resume.id],job:['前端工程师','意向岗位：前端工程师',notes.id],phone:['13812345678','手机：13812345678',resume.id],birthday:['2000-02-30','生日：2000-02-30',resume.id]};
  const fills=input.fields.filter(f=>answers[f.name]).map(f=>{const [value,quote,sourceId]=answers[f.name];return{fieldId:f.id,value,evidence:[{sourceId,quote}],reason:'根据已保存资料填写'}});
  fills.push({fieldId:'submit-button',value:'click',evidence:[{sourceId:resume.id,quote:'陈晓'}],action:'submit'});
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({model:'deepseek-flash',choices:[{finish_reason:mode==='truncated'?'length':'stop',message:{content:JSON.stringify({fills})}}],usage:{prompt_tokens:700,completion_tokens:240}})});
 });
 let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker',{timeout:20000});const id=new URL(worker.url()).host;
 await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_old_jev_fixture',profile:{base:{},education:[],work:[],custom:[],notes:'意向岗位：前端工程师'}}));
 const options=await ctx.newPage();await options.goto(`chrome-extension://${id}/options.html`);await options.locator('#notes').waitFor();
 // Seed a 0.2-style single-PDF record: the new material list must retain it.
 await options.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('jev-apply-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>{const db=r.result,tx=db.transaction('files','readwrite');tx.objectStore('files').put({name:'legacy.pdf',size:13,savedAt:'2026-09-20T00:00:00Z',enabled:false,blob:new Blob(['RAW-PDF-BYTES'],{type:'application/pdf'}),text:'DO-NOT-SEND'},'resume');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)}}));
 await options.reload();await options.locator('#pdf-info').filter({hasText:'legacy.pdf'}).waitFor();
 const text='姓名：陈晓\n城市：上海\n学历：本科\n手机：13812345678\n生日：2000-02-30\n';const textBytes=Buffer.from('\uFEFF'+text);
 await options.locator('#pdf-file').setInputFiles({name:'resume.txt',mimeType:'text/plain',buffer:textBytes});await options.locator('#status').filter({hasText:'已本地读取 TXT'}).waitFor();assert.equal(await options.locator('#material-select option').count(),2);assert.equal(await options.locator('#pdf-text').textContent(),text);assert(await options.locator('#material-enabled').isChecked());
 await options.locator('#save').click();await options.locator('#status').filter({hasText:'已保存到当前浏览器'}).waitFor();
 const target=await ctx.newPage();await target.goto(origin);
 const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#profile-info').filter({hasText:'已保存'}).waitFor();await panel.locator('#provider').selectOption('deepseek');await panel.locator('#data-notice').filter({hasText:'发送给 DeepSeek'}).waitFor();await panel.locator('summary').click();await panel.locator('#api-key').fill('sk-fixture-deepseek');await panel.locator('#save-key').click();await panel.locator('#key-info').filter({hasText:'已持久保存'}).waitFor();
 assert.equal(await worker.evaluate(async()=>(await chrome.storage.local.get('apiKey')).apiKey),'apikey_old_jev_fixture');
 async function scan(){await target.bringToFront();await panel.locator('#scan').click();await panel.locator('#status').filter({hasText:'扫描完成'}).waitFor();}
 await scan();await panel.locator('#match').click();await panel.locator('#status').filter({hasText:'匹配完成，DeepSeek'}).waitFor();assert((await panel.locator('#status').innerText()).includes('过滤 2 项'));assert((await panel.locator('#count').innerText()).startsWith('4 /'));assert((await panel.locator('#fields').innerText()).includes('resume.txt「姓名：陈晓」'));
 // Data changed after generation: block stale filling.
 await options.locator('#material-enabled').uncheck();await options.locator('#status').filter({hasText:'素材使用设置已保存'}).waitFor();await target.bringToFront();await panel.locator('#fill').click();await panel.locator('#status').filter({hasText:'素材或使用设置已变化'}).waitFor();assert.equal(await target.locator('[name=full_name]').inputValue(),'');
 await options.locator('#material-enabled').check();await options.locator('#status').filter({hasText:'素材使用设置已保存'}).waitFor();await scan();await panel.locator('#match').click();await panel.locator('#status').filter({hasText:'匹配完成，DeepSeek'}).waitFor();
 await panel.getByLabel('意向岗位 待填内容',{exact:true}).fill('前端工程师（实习）');await panel.getByLabel('意向岗位 待填内容',{exact:true}).blur();await target.bringToFront();await panel.locator('#fill').click();await panel.locator('#status').filter({hasText:'已填入 4 项'}).waitFor();
 assert.equal(await target.locator('[name=full_name]').inputValue(),'陈晓');assert.equal(await target.locator('[name=city]').inputValue(),'上海');assert.equal(await target.locator('[name=degree]').inputValue(),'b');assert.equal(await target.locator('[name=job]').inputValue(),'前端工程师（实习）');assert.equal(await target.locator('[name=phone]').inputValue(),'13900000000');assert.equal(await target.locator('[name=birthday]').inputValue(),'');assert(!(await target.locator('[name=consent]').isChecked()));assert.equal(await target.evaluate(()=>submitted),0);
 await mkdir('test-artifacts',{recursive:true});await panel.setViewportSize({width:440,height:1000});await panel.screenshot({path:'test-artifacts/deepseek-panel.png',fullPage:true});await options.screenshot({path:'test-artifacts/materials.png',fullPage:true});
 for(const [nextMode,expected]of [['malformed','无效 JSON'],['truncated','结果不完整'],['unauthorized','密钥无效']]){mode=nextMode;await scan();await panel.locator('#match').click();await panel.locator('#status').filter({hasText:expected}).waitFor();assert.equal(await target.evaluate(()=>submitted),0);}
 // Provider selection, separate credentials, all source files and TXT bytes survive restart.
 await ctx.close();ctx=await launch();let [restarted]=ctx.serviceWorkers();if(!restarted)restarted=await ctx.waitForEvent('serviceworker',{timeout:20000});
 const restored=await ctx.newPage();await restored.goto(`chrome-extension://${id}/options.html`);await restored.locator('#pdf-info').filter({hasText:'2 份素材'}).waitFor();const choices=await restored.locator('#material-select option').evaluateAll(os=>os.map(o=>({id:o.value,name:o.textContent})));const txtId=choices.find(x=>x.name==='resume.txt').id;await restored.locator('#material-select').selectOption(txtId);await restored.locator('#pdf-info').filter({hasText:'resume.txt'}).waitFor();assert.equal(await restored.locator('#pdf-text').textContent(),text);
 const download=restored.waitForEvent('download');await restored.locator('#download-pdf').click();const file=await download;assert.deepEqual(await readFile(await file.path()),textBytes);
 const again=await ctx.newPage();await again.goto(`chrome-extension://${id}/panel.html`);await again.locator('#provider-model').filter({hasText:'deepseek-flash'}).waitFor();assert.equal(await again.locator('#provider').inputValue(),'deepseek');await again.locator('summary').click();await again.locator('#clear-key').click();await again.locator('#key-info').filter({hasText:'未设置'}).waitFor();assert.equal(await restarted.evaluate(async()=>(await chrome.storage.local.get('apiKey')).apiKey),'apikey_old_jev_fixture');
 await again.locator('#provider').selectOption('jev');await again.locator('#key-info').filter({hasText:'已持久保存'}).waitFor();assert((await again.locator('#data-notice').innerText()).includes('不发送给 Jev'));assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'PASS',browser:process.env.BROWSER_CHANNEL||'chromium',mode:'mocked DeepSeek API',requests:requests.length,checks:['legacy PDF retained','multiple PDF/TXT materials','UTF-8 BOM text','provider and key isolation','source-backed plan','unknown field and invalid date rejected','editable preview','native fill','skip existing and no submit','stale materials blocked','malformed/truncated/auth errors','restart persistence','original TXT bytes recovered']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
