import {chromium} from 'playwright';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import path from 'node:path';
import {pageBridge} from '../src/page.js';import {PLATFORM_TEMPLATES} from '../src/platform-templates.js';
const baseline=process.env.BASELINE_PAGE?(await import(pathToFileURL(path.resolve(process.env.BASELINE_PAGE)))).pageBridge:null;
const browser=await chromium.launch({headless:true,channel:'chromium'});
try{
 const page=await browser.newPage();const scan=(bridge=pageBridge)=>page.evaluate(bridge,{action:'scan',token:'dynamic',platformTemplates:PLATFORM_TEMPLATES});
 const native=`<!doctype html><meta charset="utf-8"><fieldset><legend>其他信息</legend><div class="form-item"><label class="form-item__text">研究方向</label><input name="research"></div></fieldset><button id="save">保存</button><script>window.saved=0;save.onclick=()=>saved++;document.querySelector('input').onmousedown=e=>{const copy=e.target.cloneNode(true);copy.onmousedown=null;e.target.replaceWith(copy)};</script>`;
 if(baseline){await page.setContent(native);const old=await scan(baseline);const r=await page.evaluate(baseline,{action:'fill',token:'dynamic',items:[{id:old.fields[0].id,value:'机器学习'}]});assert.equal(r.results[0].ok,false,'old release must reproduce the activation-remount failure');}
 await page.setContent(native);let r=await scan();let field=r.fields[0];let written=await page.evaluate(pageBridge,{action:'fill',token:'dynamic',items:[{id:field.id,value:'机器学习',expectedCurrent:''}]});assert(written.results[0].ok,JSON.stringify(written));assert.equal(await page.locator('[name=research]').inputValue(),'机器学习');assert((await page.evaluate(pageBridge,{action:'verify',token:'dynamic',items:[{id:field.id,value:'机器学习'}]})).results[0].ok);assert.equal(await page.evaluate(()=>saved),0);
 // Replacing the entire field is allowed only inside its original surviving record.
 await page.evaluate(pageBridge,{action:'mark-review',token:'dynamic',items:[{id:field.id,value:'机器学习',mark:'uncertain'}]});await page.locator('.form-item').evaluate(e=>e.replaceWith(e.cloneNode(true)));assert((await page.evaluate(pageBridge,{action:'read-current',token:'dynamic',items:[{id:field.id}]})).results[0].ok);r=await scan();assert.equal(r.fields[0].reviewMark,'uncertain');await page.evaluate(pageBridge,{action:'mark-review',token:'dynamic',items:[{id:field.id,mark:''}]});assert.equal(await page.locator('[name=research]').evaluate(e=>e.style.outline),'','acceptance clears an inherited highlight after remount');
 await page.locator('.form-item').evaluate(e=>{const old=e.querySelector('input'),a=old.cloneNode(true),b=old.cloneNode(true);old.replaceWith(a,b)});const ambiguous=await page.evaluate(pageBridge,{action:'fill',token:'dynamic',overwrite:true,items:[{id:field.id,value:'不应写入'}]});assert.equal(ambiguous.results[0].ok,false);assert.match(ambiguous.results[0].reason,/FIELD_REPLACED/);assert.deepEqual(await page.locator('[name=research]').evaluateAll(es=>es.map(e=>e.value)),['机器学习','机器学习']);
 await page.setContent(native.replace('copy.onmousedown=null;','copy.onmousedown=null;copy.value="用户刚改";'));r=await scan();written=await page.evaluate(pageBridge,{action:'fill',token:'dynamic',items:[{id:r.fields[0].id,value:'机器学习',expectedCurrent:''}]});assert(!written.results[0].ok);assert.equal(await page.locator('[name=research]').inputValue(),'用户刚改');
 const moka=`<!doctype html><meta charset="utf-8"><div class="apply-block-test"><div class="blockTitle-test">教育背景</div><div class="apply-fields-test"><div class="apply-field-test"><div class="title-test">就读时间</div><div class="month-range-select"></div></div></div></div><button id="save">保存</button><script>
 window.saved=0;save.onclick=()=>saved++;var range=document.querySelector('.month-range-select');
 function control(unit,index,value=''){const box=document.createElement('div');box.className='sd-Dropdown-container-test';box.dataset.index=index;box.innerHTML='<label class="sd-Select-container-test"><span class="sd-Input-display-value-test">'+value+'</span><input placeholder="'+unit+'"></label>';box.querySelector('label').onclick=e=>{e.preventDefault();const old=box.querySelector('.sd-Select-menu-test');if(old){old.remove();return;}const menu=document.createElement('div');menu.className='sd-Select-menu-test';for(const option of unit==='年'?['2024年','2027年']:['01月','九月','六月']){const n=document.createElement('div');n.className='sd-Menu-content-item-test';n.textContent=option;n.onclick=e=>{e.stopPropagation();box.querySelector('span').textContent=option;menu.remove();if(unit==='年'){const old=box.nextElementSibling,replacement=control('月',Number(index)+1,'01月');old.replaceWith(replacement)}};menu.append(n)}box.append(menu)};return box;}
 for(const [i,unit]of ['年','月','年','月'].entries())range.append(control(unit,i));
 </script>`;
 if(baseline){await page.setContent(moka);const old=await scan(baseline);await page.evaluate(baseline,{action:'fill',token:'dynamic',items:[{id:old.fields[0].id,value:'2024年'}]});const r=await page.evaluate(baseline,{action:'read-current',token:'dynamic',items:[{id:old.fields[1].id}]});assert.equal(r.results[0].ok,false,'old release must reproduce the dependent-month remount failure');}
 await page.setContent(moka);r=await scan();await page.evaluate(pageBridge,{action:'fill',token:'dynamic',items:[{id:r.fields[0].id,value:'2024年'}]});await page.locator('.month-range-select label').nth(1).click();const touched=await page.evaluate(pageBridge,{action:'fill',token:'dynamic',overwrite:true,items:[{id:r.fields[1].id,value:'九月',expectedCurrent:''}]});assert.match(touched.results[0].reason,/REVIEW_CHANGED/);assert.equal(await page.locator('[class*=display-value]').nth(1).innerText(),'01月');
 await page.setContent(moka);r=await scan();for(const [i,value]of ['2024年','九月','2027年','六月'].entries()){written=await page.evaluate(pageBridge,{action:'fill',token:'dynamic',overwrite:true,items:[{id:r.fields[i].id,value,expectedCurrent:''}]});assert(written.results[0].ok,JSON.stringify(written));}
 assert.deepEqual(await page.locator('[class*=display-value]').allTextContents(),['2024年','九月','2027年','六月']);assert.equal(await page.evaluate(()=>saved),0);
 // aria-controls may point into a portal listbox rather than at its outer element.
 await page.setContent(`<!doctype html><meta charset="utf-8"><label>学历<input role="combobox" aria-controls="inside" aria-label="学历" readonly></label><div role="listbox" id="menu" style="display:none"><span id="inside"></span><div role="option">本科</div><div role="option">硕士</div></div><div role="listbox"><div role="option">无关提示</div></div><button id="save">保存</button><script>window.saved=0;save.onclick=()=>saved++;const input=document.querySelector('input');input.onclick=()=>setTimeout(()=>menu.style.display='block',120);input.onkeydown=e=>{if(e.key==='Escape')menu.style.display='none'};document.querySelectorAll('#menu [role=option]').forEach(n=>n.onclick=()=>{input.value=n.textContent;menu.style.display='none'});const Original=window.MutationObserver;window.observers=0;window.MutationObserver=class extends Original{observe(...a){if(!this.live){observers++;this.live=true}super.observe(...a)}disconnect(){if(this.live){observers--;this.live=false}super.disconnect()}};</script>`);
 r=await scan();assert(r.fields[0].supported,JSON.stringify(r.fields));written=await page.evaluate(pageBridge,{action:'fill',token:'dynamic',items:[{id:r.fields[0].id,value:'硕士'}]});assert(written.results[0].ok,JSON.stringify(written));assert.equal(await page.locator('input').inputValue(),'硕士');assert.equal(await page.evaluate(()=>observers),0,'operation observers must be cleaned up');assert.equal(await page.evaluate(()=>saved),0);
 console.log(JSON.stringify({result:'PASS',baselineCompared:!!baseline,checks:['input remount on activation','whole field replacement scoped to surviving record','uncertain warning survives remount and clears on acceptance','ambiguous duplicates refused','activation-time user edit preserved','year remounts month but owned default remains writable','trusted interaction on regenerated month removes default ownership','Chinese and unit-labelled month committed','ARIA inner node resolves outer portal listbox despite unrelated menu','delayed visibility wakes bounded observer','observers cleaned up','no website save']}));
}finally{await browser.close();}
