import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html=`<!doctype html><meta charset="utf-8"><form><label>培养方式<select name="study"><option value="">请选择</option><option value="full">全日制</option></select></label><label>毕业时间<input type="date" name="graduation"></label><label>研究方向<input name="research"></label><label>被清空的字段<input name="discard"></label><button>保存</button></form><script>window.submits=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};document.querySelector('[name=discard]').onchange=e=>setTimeout(()=>e.target.value='',100);</script>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'resume-feedback-')),extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));let ctx,calls=0,blockModels=false;
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
 await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_feedback_fixture',deepseekApiKey:'sk-feedback-fixture',profile:{base:{},notes:'培养方式：全日制\n毕业时间：2027-06-01\n研究方向：机器学习\n被清空的字段：测试值',education:[],work:[],custom:[]}}));
 await ctx.route('https://api.typesafe.ai/**',async route=>{calls++;assert(!blockModels);const p=route.request().postDataJSON(),answers={};if(p.state.stage==='route')p.state.fields.forEach((f,i)=>{const choice=(p.state.ranges.find(r=>r.sourceId==='notes')||p.state.ranges[0]).id;answers['q'+i]={type:'choice',choice,confidence:.99,probabilities:{[choice]:.99}}});else {assert.fail('Fast mode should not audit');}await route.fulfill({json:{answers}});});
 await ctx.route('https://api.deepseek.com/**',async route=>{calls++;assert(!blockModels);const input=JSON.parse(route.request().postDataJSON().messages.at(-1).content),values={study:['full','全日制'],graduation:['2027-06-01','2027-06-01'],research:['机器学习','机器学习'],discard:['测试值','测试值']};const fills=input.revisionFeedback.length?[]:input.fields.map(f=>({fieldId:f.id,rangeId:input.assignments.find(a=>a.fieldId===f.id).range.id,value:values[f.name][0],quote:values[f.name][1]}));await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills})}}]}});});
 const target=await ctx.newPage();await target.goto(origin);const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#team-keys').filter({hasText:'DeepSeek：已配置'}).waitFor();await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 3 项（其中 3 项已标橙待确认）'}).waitFor();
 assert.equal(await panel.getByLabel('培养方式 待填内容',{exact:true}).inputValue(),'full');assert.equal(await target.locator('[name=study]').inputValue(),'full');assert.equal(await panel.locator('.needs-confirmation').count(),3);assert.equal(await panel.locator('#fields .field').count(),3);assert.equal(await panel.getByLabel('填入 被清空的字段',{exact:true}).count(),0);assert((await target.locator('[name=study]').evaluate(e=>e.closest('label').style.outline)).includes('rgb(213, 138, 0)'));
 const before=calls;await panel.getByLabel('培养方式 确认并记住',{exact:true}).click();await panel.locator('#status').filter({hasText:'已记住 1 项'}).waitFor();assert.equal(await target.locator('[name=study]').inputValue(),'full');assert.equal(calls,before);assert.equal(await panel.getByLabel('培养方式 确认并记住',{exact:true}).count(),0);
 await panel.getByLabel('研究方向 待填内容',{exact:true}).fill('机器学习与评测');await panel.getByLabel('研究方向 待填内容',{exact:true}).blur();
 for(const label of ['毕业时间','研究方向'])await panel.getByLabel('填入 '+label,{exact:true}).check();await panel.locator('#confirm-fill').click();await panel.locator('#status').filter({hasText:'已记住 2 项'}).waitFor();
 assert.equal(await target.locator('[name=graduation]').inputValue(),'2027-06-01');assert.equal(await target.locator('[name=research]').inputValue(),'机器学习与评测');assert.equal(await target.locator('[name=discard]').inputValue(),'');assert.equal(calls,before);assert.equal(await panel.locator('.needs-confirmation').count(),0);assert.equal(await panel.locator('#fields .field').count(),0);assert.equal(await panel.locator('#review-empty').innerText(),'没有橙色待确认项。');assert.equal(await panel.locator('#confirm-fill').isDisabled(),true);
 const saved=(await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts;assert.equal(saved.length,3);assert(saved.every(f=>f.scope==='site'));assert.equal(saved.find(f=>f.label==='培养方式').value,'全日制');assert(!saved.some(f=>f.label==='被清空的字段'));
 // New page, reloaded panel, different option IDs: saved feedback is sufficient without either AI.
 await target.reload();await target.locator('[name=discard]').evaluate(e=>e.value='保留已有');await target.locator('[name=study] option').last().evaluate(e=>e.value='changed-id');await panel.reload();await panel.locator('#team-keys').filter({hasText:'DeepSeek：已配置'}).waitFor();blockModels=true;await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 3 项'}).waitFor();assert.equal(calls,before);assert.equal(await target.locator('[name=study]').inputValue(),'changed-id');assert.equal(await target.locator('[name=research]').inputValue(),'机器学习与评测');assert.equal(await target.locator('[name=discard]').inputValue(),'保留已有');assert.equal(await target.evaluate(()=>submits),0);
 async function freshResearch(){await worker.evaluate(async()=>{const {learnedFacts}=await chrome.storage.local.get('learnedFacts');await chrome.storage.local.set({learnedFacts:learnedFacts.filter(f=>f.label!=='研究方向')});});await target.locator('[name=research]').fill('');blockModels=false;await target.bringToFront();await panel.locator('#collaborate').click();await panel.waitForFunction(()=>!document.querySelector('#collaborate').disabled);assert.match(await panel.locator('#status').innerText(),/协作完成：已填入并核验 1 项（其中 1 项已标橙/);assert.equal(await panel.locator('#fields .field').count(),1);}
 await freshResearch();
 await target.locator('[name=research]').fill('网页中确认的研究方向');await panel.getByLabel('研究方向 采用网页修改',{exact:true}).click();await panel.locator('#status').filter({hasText:'已记住 1 项'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts.find(f=>f.label==='研究方向').value,'网页中确认的研究方向');
 await freshResearch();await panel.getByLabel('研究方向 拒绝此答案',{exact:true}).click();await panel.locator('#status').filter({hasText:'已记住拒绝'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('rejectedAnswers'))).rejectedAnswers.length,1);assert.equal(await target.locator('[name=research]').inputValue(),'机器学习');assert.equal(await panel.locator('#fields .field').count(),0);
 const options=await ctx.newPage();await options.goto(`chrome-extension://${id}/options.html`);await options.getByRole('button',{name:'撤销拒绝',exact:true}).click();await options.locator('#status').filter({hasText:'已撤销拒绝'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('rejectedAnswers'))).rejectedAnswers.length,0);
 await freshResearch();
 // Stale previews cannot be confirmed against another active tab.
 const other=await ctx.newPage();await other.goto(origin);await other.bringToFront();await panel.getByLabel('研究方向 确认并记住',{exact:true}).click();await panel.locator('#status').filter({hasText:'当前标签页与预览不一致'}).waitFor();assert.equal(await other.locator('[name=research]').inputValue(),'');
 console.log(JSON.stringify({result:'PASS',checks:['fast mode skips independent audits','single confirmation bypasses AI','edited batch confirmation','only verified writes remembered','option labels survive new IDs','reload reuses feedback with zero AI calls','preserves existing values','stale tab rejected','direct webpage edit feedback','rejection persists and can be undone','only orange cards shown','accepted and rejected cards disappear','empty state and disabled batch action','no submit']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
