import {chromium} from 'playwright';import {mkdtemp,cp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=await mkdtemp(path.join(tmpdir(),'resume-errors-'));const extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});let ctx;
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{headless:true,channel:'chromium',args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;const page=await ctx.newPage();await page.goto(`chrome-extension://${id}/options.html`);await page.locator('#learned-facts').filter({hasText:'还没有学习资料'}).waitFor();
 async function file(buffer,name='private-name.txt',expected){await page.locator('#pdf-file').setInputFiles({name,mimeType:'text/plain',buffer});await page.waitForFunction(()=>!document.querySelector('#pdf-file').disabled);const status=await page.locator('#status').textContent();if(expected){assert(status.includes('['+expected+']'),status);const report=JSON.parse(await page.locator('#diagnostic-text').inputValue());assert.equal(report[0].code,expected);assert(!JSON.stringify(report).includes('private-name'));assert(!JSON.stringify(report).includes('PRIVATE-ERROR'));return report[0];}assert(status.includes('已本地读取 TXT'),status);}
 await file(Buffer.from('已保存的素材\r\n'));assert.equal(await page.locator('#material-select option').count(),1);
 await file(Buffer.from([0x81]),'bad.txt','TXT_ENCODING');await file(Buffer.from('  \r\n'),'empty.txt','TXT_EMPTY');await file(Buffer.from('%PDF-1.7'),'fake.txt','TXT_FORMAT');await file(Buffer.alloc(2*1024*1024+1),'big.txt','FILE_SIZE');await file(Buffer.from('text'),'wrong.docx','FILE_TYPE');
 await page.evaluate(()=>{window.originalArrayBuffer=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async()=>{throw new DOMException('PRIVATE-ERROR','NotReadableError')};});const read=await file(Buffer.from('text'),'read.txt','FILE_READ');assert.equal(read.stage,'read');await page.evaluate(()=>File.prototype.arrayBuffer=window.originalArrayBuffer);
 await page.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('PRIVATE-ERROR','QuotaExceededError')};});const quota=await file(Buffer.from('text'),'quota.txt','STORE_QUOTA');assert.equal(quota.stage,'store');assert.equal(quota.persisted,false);await page.evaluate(()=>IDBObjectStore.prototype.put=window.originalPut);
 assert.equal(await page.locator('#material-select option').count(),1);assert.equal(await page.locator('#pdf-text').textContent(),'已保存的素材\r\n');await file(Buffer.from('再次成功'));assert.equal(await page.locator('#material-select option').count(),2);assert(await page.locator('#import-diagnostic').isHidden());
 await page.locator('#json-file').setInputFiles({name:'resume.txt',mimeType:'text/plain',buffer:Buffer.from('私人素材')});await page.locator('#status').filter({hasText:'PROFILE_TYPE'}).waitFor();assert((await page.locator('#status').textContent()).includes('页面顶部'));
 await page.evaluate(()=>window.dispatchEvent(new ErrorEvent('error',{error:new TypeError('PRIVATE-ERROR')})));const startup=await page.locator('#status').textContent();assert(startup.includes('[UI_SCRIPT_FAILED]'));assert(!startup.includes('PRIVATE-ERROR'));
 console.log(JSON.stringify({result:'PASS',checks:['encoding/empty/format/size/type diagnosis','file read and quota failures by stage','reports redact filename and raw exception','old material retained after failure','retry works','uncaught UI error guard']}));
}finally{if(ctx)await ctx.close();await rm(root,{recursive:true,force:true});}
