import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html=`<!doctype html><meta charset="utf-8"><title>延迟清空</title><form><label>研究方向<input name="research"></label><button>保存</button></form><script>window.submits=0;window.blurs=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};let committed='',activated=false;document.querySelector('input').onclick=()=>setTimeout(()=>activated=true,60);document.querySelector('input').oninput=e=>{if(!activated){e.target.value=committed;return;}if(e instanceof InputEvent&&e.data)setTimeout(()=>committed=e.target.value,30);else committed=e.target.value;};document.querySelector('input').onblur=e=>{blurs++;e.target.value=committed;};</script>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'resume-late-')),extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));let ctx;
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
 await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_late_fixture',deepseekApiKey:'sk-late-fixture',profile:{base:{},notes:'研究方向：机器学习',education:[],work:[],custom:[]}}));
 await ctx.route('https://api.typesafe.ai/**',async route=>{const p=route.request().postDataJSON(),choice=p.state.ranges[0].id;await route.fulfill({json:{answers:{q0:{type:'choice',choice,confidence:1,probabilities:{[choice]:1}}}}});});
 await ctx.route('https://api.deepseek.com/**',async route=>{const p=JSON.parse(route.request().postDataJSON().messages.at(-1).content);await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills:[{fieldId:p.fields[0].id,rangeId:p.assignments[0].range.id,value:'机器学习',quote:'机器学习'}]})}}]}});});
 const target=await ctx.newPage();await target.goto(origin);
 // Reproduce side-panel focus: the first native blur emits no event.
 await worker.evaluate(async origin=>{const tab=(await chrome.tabs.query({})).find(t=>t.url?.startsWith(origin));await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{const el=document.querySelector('input');el.blur=()=>{delete el.blur;};}});},origin);
 const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);
 async function run(){await panel.locator('#team-keys').filter({hasText:'DeepSeek：已配置'}).waitFor();await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 1 项'}).waitFor();}
 await run();assert((await target.evaluate(()=>blurs))>0);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('executedPlanCache'))).executedPlanCache.length,1);
 await target.evaluate(()=>setTimeout(()=>document.querySelector('input').value='',2500));
 await panel.locator('#status').filter({hasText:'已填入并核验 0 项'}).waitFor({timeout:12000});assert.match(await panel.locator('#status').innerText(),/填写失败 1 项/);assert.equal(await panel.locator('.needs-confirmation').count(),1);assert.match(await panel.locator('#fields').innerText(),/VALUE_CHANGED/);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('executedPlanCache'))).executedPlanCache.length,0);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts,undefined);assert.equal(await target.locator('input').inputValue(),'');
 // A user correction is never overwritten and may be explicitly accepted.
 await target.locator('input').fill('用户核对后的研究方向');await panel.getByLabel('研究方向 采用网页修改',{exact:true}).click();await panel.locator('#status').filter({hasText:'已记住 1 项'}).waitFor();await new Promise(r=>setTimeout(r,3200));assert.equal(await target.locator('input').inputValue(),'用户核对后的研究方向');assert.equal(await panel.locator('.needs-confirmation').count(),0);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts[0].value,'用户核对后的研究方向');assert.equal(await target.evaluate(()=>submits),0);
 console.log(JSON.stringify({result:'PASS',checks:['click activation and deferred state before blur','missing native blur event fallback','late clear detected after completion','success count corrected','orange failure visible','failed cache removed','no automatic overwrite or learning','explicit webpage correction accepted without recurring stale warning','no submit']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
