import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {pageBridge} from '../src/page.js';
const field=(label,control)=>`<div class="ant-form-item"><div class="ant-form-item-label"><label>${label}<span class="labelRequired">*</span></label></div><div>${control}</div></div>`;
const section=(title,rows)=>`<div class="form-cell"><div class="tit-wrap"><div class="tit"><p>${title}</p><span>必填</span></div></div><div class="form-cell-right">${rows.map(r=>`<div class="form-cell-inner">${r}</div>`).join('')}</div></div>`;
const skills='准备好的技能原文。\n\n  第二行保留空白。';
const filled=`<!doctype html><meta charset="utf-8"><title>已填简历</title><form>${section('个人基本信息',[field('姓名','<input value="示例本人">')+field('移动电话','<input value="13900000001">')+field('出生日期','<input readonly value="2001-03-04">')+field('民族','<div class="ant-select-selection" role="combobox"><div class="ant-select-selection-selected-value">测试选项</div><input value="搜索词不能学"></div>')+field('性别','<div class="ant-radio-group"><label><input type="radio" value="opaque-1" checked>男</label><label><input type="radio" value="opaque-2">女</label></div>')+field('岗位调剂方向','<div class="ant-checkbox-group"><label><input type="checkbox" checked>研发</label><label><input type="checkbox">销售</label></div>')+field('密码','<input type="password" value="NEVER_CAPTURE">')+field('声明','<textarea>NEVER_CAPTURE</textarea>')])}${section('教育经历',[field('学校','<input value="示例甲大学">')+field('开始时间','<input readonly value="2024-09-01">'),field('学校','<input value="示例乙大学">')+field('开始时间','<input readonly value="2020-09-01">')])}${section('家庭关系',[field('姓名','<input value="示例父亲">')])}${section('自我评价',[field('评价内容',`<textarea>${skills}</textarea>`)])}<button id="save" type="button">保存</button></form><script>window.events=0;['input','change','click'].forEach(t=>document.addEventListener(t,()=>events++));</script>`;
const targetHtml=`<!doctype html><meta charset="utf-8"><title>另一招聘页面</title><form><label>手机号<input name="phone"></label><label>个人能力<textarea name="skills"></textarea></label><button id="submit">提交</button></form><script>window.submits=0;document.querySelector('form').onsubmit=e=>{e.preventDefault();submits++};</script>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(req.url==='/filled'?filled:targetHtml)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'resume-learn-')),extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));let ctx,calls=0;
const launch=()=>chromium.launchPersistentContext(path.join(root,'profile'),{headless:true,channel:'chromium',args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
try{
 ctx=await launch();let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_learning_fixture',deepseekApiKey:'sk-learning-fixture',profile:{base:{phone:'13900000000'},education:[],work:[],custom:[],notes:''}}));
 await ctx.route('https://api.deepseek.com/**',async route=>{calls++;const input=JSON.parse(route.request().postDataJSON().messages.at(-1).content);const fills=input.fields.map(f=>{const candidates=input.passages.filter(p=>f.candidatePassageIds.includes(p.id));assert(candidates.length===1,JSON.stringify(candidates));assert(candidates[0].sourceId.startsWith('learned:'));return {fieldId:f.id,passageId:candidates[0].id};});await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills})}}]}});});
 await ctx.route('https://api.typesafe.ai/**',async route=>{calls++;const p=route.request().postDataJSON(),answers={};p.state.items.forEach((item,i)=>{assert(item.evidence[0].learned);assert(p.questions[`q${i}_conflict`].instructions.includes('explicit correction'));answers[`q${i}_policy`]={type:'choice',choice:'fact',confidence:1,probabilities:{fact:1}};for(const k of ['fit','unsupported','conflict'])answers[`q${i}_${k}`]={type:'noul',noul:k==='fit'?1:0};});await route.fulfill({json:{answers}});});
 const target=await ctx.newPage();await target.goto(origin+'/filled');const direct=await target.evaluate(pageBridge,{action:'capture',token:'read'});
 assert.equal(await target.evaluate(()=>events),0);assert(direct.fields.every(f=>f.capturedValue&&!f.capturedValue.includes('NEVER_CAPTURE')&&!f.capturedValue.includes('搜索词')));assert.equal(direct.fields.find(f=>f.label==='性别').capturedValue,'男');assert.equal(direct.fields.find(f=>f.label==='岗位调剂方向').capturedValue,'研发');assert.equal(direct.fields.find(f=>f.label==='出生日期').capturedValue,'2001-03-04');assert(direct.fields.some(f=>f.context.startsWith('教育经历 · 第 2 条')));assert.equal(direct.fields.find(f=>f.label==='评价内容').capturedValue,skills);
 const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#profile-info').filter({hasText:'已保存'}).waitFor();await target.bringToFront();await panel.locator('#capture-page').click();await panel.locator('#learning-preview').waitFor();assert.equal(calls,0);assert.equal(await target.evaluate(()=>events),0);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts,undefined);
 const family=panel.locator('[data-learning-id]').filter({has:panel.locator('p.muted').filter({hasText:'家庭关系'})});assert.equal(await family.locator('input[type=checkbox]').isChecked(),false);
 await panel.getByLabel('学习内容 移动电话',{exact:true}).fill('13900000002');await panel.locator('#save-learning').click();await panel.locator('#status').filter({hasText:'确认资料保存到本机'}).waitFor();let saved=await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'));assert(saved.learnedFacts.length>=8);assert.equal(saved.learnedFacts.find(f=>f.label==='移动电话').value,'13900000002');assert(!saved.learnedFacts.some(f=>f.category==='family'));assert.equal(calls,0);
 const before=saved.learnedFacts.length;await target.bringToFront();await panel.locator('#capture-page').click();await panel.locator('#learning-preview').waitFor();await panel.getByLabel('学习内容 移动电话',{exact:true}).fill('13900000002');await panel.locator('#save-learning').click();await panel.locator('#status').filter({hasText:'确认资料保存到本机'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts.length,before);
 await target.goto(origin+'/blank');await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 2 项'}).waitFor();assert.equal(await target.locator('[name=phone]').inputValue(),'13900000002');assert.equal(await target.locator('[name=skills]').inputValue(),skills);assert.equal(await target.evaluate(()=>submits),0);assert(calls>=2);
 const options=await ctx.newPage();await options.goto(`chrome-extension://${id}/options.html`);const row=options.locator('[data-learned-id]').filter({hasText:'移动电话'});await row.waitFor();await row.locator('textarea').fill('13900000003');await row.getByRole('button',{name:'保存这项',exact:true}).click();await options.locator('#status').filter({hasText:'已更新该学习资料'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts.find(f=>f.label==='移动电话').value,'13900000003');

 const downloadEvent=options.waitForEvent('download');await options.locator('#export').click();const download=await downloadEvent;const exported=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(exported.learnedFacts.length,before);assert.equal(exported.learnedFacts.find(f=>f.label==='移动电话').value,'13900000003');assert.equal(exported.base.phone,'13900000000');
 const editable=options.locator('[data-learned-id]').filter({hasText:'移动电话'});await editable.locator('input[type=checkbox]').uncheck();await editable.getByRole('button',{name:'保存这项',exact:true}).click();await options.locator('#status').filter({hasText:'已更新该学习资料'}).waitFor();await options.waitForFunction(()=>!document.querySelector('[data-learned-id] textarea[aria-label="已学习 移动电话"]').closest('[data-learned-id]').querySelector('input[type=checkbox]').checked);
 assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts.find(f=>f.label==='移动电话').enabled,false);
 await options.locator('#json-file').setInputFiles({name:'profile.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await options.locator('#status').filter({hasText:'资料已导入预览'}).waitFor();await options.locator('#save').click();await options.locator('#status').filter({hasText:'个人资料已保存到当前浏览器'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts.find(f=>f.label==='移动电话').enabled,true);
 await ctx.close();ctx=await launch();[worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');saved=await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'));assert.equal(saved.learnedFacts.length,before);assert.equal(saved.learnedFacts.find(f=>f.label==='移动电话').value,'13900000003');
 const page=await ctx.newPage();await page.setContent('<div class="form-cell"><div class="tit-wrap"><div class="tit"><p>个人基本信息</p></div></div><div class="form-cell-inner">'+Array.from({length:125},(_,i)=>field('资料'+i,`<input value="值${i}">`)).join('')+'</div></div>');const large=await page.evaluate(pageBridge,{action:'capture',token:'large'});assert.equal(large.fields.length,125);assert.equal(large.atLimit,false);
 const long='完整选项'.repeat(80);await page.setContent('<label>选项<select><option>'+long+'</option></select></label><div class=ant-form-item><div class=ant-form-item-label>自定义选项</div><div role=combobox class=ant-select-selection><div class=ant-select-selection-selected-value>'+long+'</div></div></div>');const longCapture=await page.evaluate(pageBridge,{action:'capture',token:'long'});assert(longCapture.fields.every(f=>f.capturedValue===long));assert.equal(longCapture.fields.length,2);
 await page.setContent('<label>已确认锁定值<input disabled value=锁定原文></label>');const locked=await page.evaluate(pageBridge,{action:'capture',token:'locked'});assert.equal(locked.fields[0].capturedValue,'锁定原文');const scanLocked=await page.evaluate(pageBridge,{action:'scan',token:'locked-scan'});assert.equal(scanLocked.fields.length,0);
 console.log(JSON.stringify({result:'PASS',checks:['Hotjob read-only capture with no clicks/input/change events','human option labels, radio and checkbox selections, readonly dates','record and family separation','no API or persistence before confirmation','edited confirmation and deduplication','learned correction and synonym used by both AI stages','verbatim multiline reuse','manager edits, disabling, export/import and restart persistence','125 fields captured without old 100-field truncation','no website save or submit']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
