import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html='<form><label>学校名称<input name="school"></label><label>开始月份<input type="month" name="start"></label><label>被清空的字段<input name="discard"></label><button>保存</button></form><script>window.submits=0;document.querySelector("form").onsubmit=e=>{e.preventDefault();submits++};document.querySelector("[name=discard]").onchange=e=>setTimeout(()=>e.target.value="",100)</script>';
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const root=await mkdtemp(path.join(tmpdir(),'resume-manual-'));const extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));let ctx;
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});let calls=0;await ctx.route('https://api.**/*',r=>{calls++;return r.abort()});let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;const target=await ctx.newPage();await target.goto(origin);const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#profile-info').waitFor();await target.bringToFront();await panel.locator('#scan').click();await panel.locator('#status').filter({hasText:'扫描完成'}).waitFor();
 async function one(label,value,expected){await panel.waitForFunction(()=>!document.querySelector('#scan').disabled);const card=panel.locator('.field').filter({has:panel.locator('.field-title').filter({hasText:label})});await card.locator('summary').click();await card.getByLabel(label+' 手动待填值',{exact:true}).fill(value);await card.getByRole('button',{name:'仅填此项',exact:true}).click();await panel.waitForFunction(()=>!document.querySelector('#scan').disabled);await panel.locator('#status').filter({hasText:expected}).waitFor();}
 await one('学校名称','示例大学','已填入 1 项');assert.equal(await target.locator('[name=school]').inputValue(),'示例大学');assert.equal(await target.locator('[name=start]').inputValue(),'');
 await one('开始月份','2024.09','已填入 1 项');assert.equal(await target.locator('[name=start]').inputValue(),'2024-09');
 await one('被清空的字段','原文内容','已填入 0 项');assert((await panel.locator('#fields').innerText()).includes('网页未保留预期值'));assert.equal(await target.locator('[name=discard]').inputValue(),'');
 assert.equal(calls,0);assert.equal(await target.evaluate(()=>submits),0);console.log(JSON.stringify({result:'PASS',checks:['manual single-field entry without profile or models','only selected field executed','month formatting','delayed readback failure is reported','no submit']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
