import {chromium} from 'playwright';import assert from 'node:assert/strict';import {pageBridge} from '../src/page.js';
const browser=await chromium.launch({headless:true,channel:'chromium'});
try{const page=await browser.newPage();await page.setContent(`<!doctype html><meta charset="utf-8"><div class="apply-block-test"><div class="blockTitle-test">教育背景</div><div class="apply-fields-test"><div class="apply-field-test"><div class="title-test">就读时间</div><div class="month-range-select"></div></div><div class="apply-field-test" id="school"><div class="title-test">学校名称</div></div><div class="apply-field-test" id="major"><div class="title-test">专业名称</div></div></div></div><button id="save">保存</button><script>
window.saved=0;save.onclick=()=>saved++;const range=document.querySelector('.month-range-select');
function control(host,placeholder){const box=document.createElement('div');box.className='sd-Dropdown-container-test';box.innerHTML='<label class="sd-Select-container-test"><span class="sd-Input-display-value-test"></span><input placeholder="'+placeholder+'"></label>';host.append(box);return box;}
function menu(box,values){box.querySelector('.sd-Select-menu-test')?.remove();const m=document.createElement('div');m.className='sd-Select-menu-test';values.forEach(v=>{const o=document.createElement('div');o.className='sd-Menu-content-item-test';o.textContent=v;o.onclick=e=>{e.stopPropagation();box.querySelector('span').textContent=v;box.querySelector('input').value='';m.remove();if(box.closest('#school')){const old=major.firstElementChild.nextElementSibling;const clone=old.cloneNode(true);clone.querySelector('input').oninput=old.querySelector('input').oninput;old.replaceWith(clone);}if(box.dataset.year){const month=box.nextElementSibling.querySelector('span');if(!month.textContent)month.textContent='1';}};m.append(o)});box.append(m);return m;}
['年','月','年','月'].forEach((unit,i)=>{const box=control(range,unit);if(unit==='年')box.dataset.year='yes';if(i===3)box.querySelector('span').textContent='7';box.querySelector('label').onclick=e=>{e.preventDefault();if(box.querySelector('.sd-Select-menu-test'))box.querySelector('.sd-Select-menu-test').remove();else menu(box,unit==='年'?['2024','2026']:Array.from({length:12},(_,i)=>String(i+1)));};});
for(const [host,label,exact]of [[school,'请输入就读学校','示例大学'],[major,'请输入专业名称','']]){const box=control(host,label),input=box.querySelector('input');input.oninput=event=>{const input=event.target,box=input.closest('.sd-Dropdown-container-test');const query=input.value;setTimeout(()=>{if(input.value!==query)return;const m=menu(box,exact&&query===exact?[exact]:[]);if(!exact&&query){const add=document.createElement('span');add.textContent='添加专业全称';add.onclick=()=>{add.remove();const custom=document.createElement('div');custom.className='custom-option-test';custom.innerHTML='<input placeholder="请输入就读专业全称"><button type="button">添加</button>';custom.querySelector('button').onclick=()=>{box.querySelector('span').textContent=custom.querySelector('input').value;box.querySelector('input').value='';m.remove();const clone=box.cloneNode(true);box.replaceWith(clone);};m.append(custom);};m.append(add);}},450);};}
</script>`);
let scan=await page.evaluate(pageBridge,{action:'scan',token:'gaps'});const get=label=>scan.fields.find(f=>f.label===label);assert.equal(get('学校名称').supported,true,'lazy search must be supported');assert.equal(get('专业名称').supported,true);
const startYear=get('就读时间 · 开始年份'),startMonth=get('就读时间 · 开始月份'),endYear=get('就读时间 · 结束年份'),endMonth=get('就读时间 · 结束月份');
let first=await page.evaluate(pageBridge,{action:'fill',token:'gaps',items:[{id:startYear.id,value:'2024'}]});assert(first.results[0].ok);scan=await page.evaluate(pageBridge,{action:'scan',token:'gaps'});assert.equal(get('就读时间 · 开始月份').hasValue,false,'owned default survives rescan');
let r=await page.evaluate(pageBridge,{action:'fill',token:'gaps',items:[{id:startMonth.id,value:'9'},{id:endYear.id,value:'2026'},{id:endMonth.id,value:'6'}]});assert(r.results.slice(0,2).every(x=>x.ok),JSON.stringify(r));assert.match(r.results[2].reason,/已有内容/);assert.equal(await page.locator('.month-range-select [class*=display-value]').nth(1).innerText(),'9');assert.equal(await page.locator('.month-range-select [class*=display-value]').nth(3).innerText(),'7');
for(const [label,value]of [['学校名称','示例大学'],['专业名称','机械工程（原文专业全称）']]){const f=get(label);r=await page.evaluate(pageBridge,{action:'fill',token:'gaps',items:[{id:f.id,value}]});assert(r.results[0].ok,JSON.stringify(r));const v=await page.evaluate(pageBridge,{action:'verify',token:'gaps',items:[{id:f.id,value}]});assert(v.results[0].ok,JSON.stringify(v));}
const major=get('专业名称');await page.locator('#major [class*=display-value]').evaluate(e=>e.textContent='用户刚修改的专业');const race=await page.evaluate(pageBridge,{action:'fill',token:'gaps',overwrite:true,items:[{id:major.id,value:'机械工程（原文专业全称）',expectedCurrent:'机械工程（原文专业全称）'}]});assert.match(race.results[0].reason,/REVIEW_CHANGED/);assert.equal(await page.locator('#major [class*=display-value]').innerText(),'用户刚修改的专业');
assert.equal(await page.evaluate(()=>saved),0);console.log(JSON.stringify({result:'PASS',checks:['year-induced default month can be replaced','pre-existing month preserved','lazy school remote lookup','explicit custom major full name','readback after control replacement','no website save']}));
}finally{await browser.close();}
