import {chromium} from 'playwright';import {mkdtemp,cp,readFile,writeFile,mkdir,rm,chmod} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
if(process.platform!=='darwin')throw Error('This integration test uses macOS native-host registration; on Windows run tests/native-host.test.py.');
const root=await mkdtemp(path.join(tmpdir(),'resume native test ')),extension=path.join(root,'extension'),native=path.join(root,'native');const host='com.resumefill.test'+Date.now();const registrations=[];let ctx;
const quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
await cp('dist',extension,{recursive:true});for(const file of ['background.js','panel.js','options.js']){const p=path.join(extension,file);await writeFile(p,(await readFile(p,'utf8')).replaceAll('com.resumefill.assistant',host));}
await mkdir(native);await cp('native/host.py',path.join(native,'host.py'));const python=execFileSync('python3',['-c','import sys;print(sys.executable)'],{encoding:'utf8'}).trim();const launcher=path.join(native,'host.command');await writeFile(launcher,`#!/bin/sh\nexec ${quote(python)} ${quote(path.join(native,'host.py'))} "$@"\n`);await chmod(launcher,0o700);
const launch=profile=>chromium.launchPersistentContext(path.join(root,profile),{headless:true,channel:'chromium',args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
try{
 ctx=await launch('profile1');let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
 const manifest=JSON.stringify({name:host,description:'isolated fixture',path:launcher,type:'stdio',allowed_origins:[`chrome-extension://${id}/`]});await writeFile(path.join(native,'native-host.json'),manifest);
 for(const profile of ['profile1','profile2']){const folder=path.join(root,profile,'NativeMessagingHosts');await mkdir(folder,{recursive:true});const location=path.join(folder,host+'.json');await writeFile(location,manifest,{flag:'wx',mode:0o600});registrations.push(location);}
 await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_pc_fixture',deepseekApiKey:'sk-pc-fixture'}));let panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#pc-key-status').filter({hasText:'PC 文件已连接'}).waitFor({state:'attached',timeout:10000}).catch(async e=>{console.error(await panel.locator('#pc-key-status').textContent());console.error(await worker.evaluate(async name=>{try{return await chrome.runtime.sendNativeMessage(name,{action:'status'})}catch(err){return {error:err.message}}},host));throw e;});let disk=JSON.parse(await readFile(path.join(root,'api-keys.json'),'utf8'));assert.deepEqual(disk.keys,{jev:'apikey_pc_fixture',deepseek:'sk-pc-fixture'});
 await panel.locator('summary').filter({hasText:'设置当前服务的 API key'}).click();await panel.locator('#provider').selectOption('deepseek');await panel.locator('#api-key').fill('sk-pc-updated-fixture');await panel.locator('#save-key').click();await panel.locator('#status').filter({hasText:'已保存到 PC 文件和浏览器'}).waitFor();assert.equal(JSON.parse(await readFile(path.join(root,'api-keys.json'),'utf8')).keys.deepseek,'sk-pc-updated-fixture');
 // Fresh extension storage/profile simulates removing and reinstalling the same extension ID.
 await ctx.close();await rm(path.join(root,'profile1'),{recursive:true,force:true});ctx=await launch('profile2');[worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#pc-key-status').filter({hasText:'PC 文件已连接'}).waitFor({state:'attached'});const restored=await worker.evaluate(()=>chrome.storage.local.get(['apiKey','deepseekApiKey']));assert.deepEqual(restored,{apiKey:'apikey_pc_fixture',deepseekApiKey:'sk-pc-updated-fixture'});
 await panel.locator('summary').filter({hasText:'设置当前服务的 API key'}).click();await panel.locator('#clear-key').click();await panel.locator('#key-info').filter({hasText:'未设置'}).waitFor({state:'attached'});disk=JSON.parse(await readFile(path.join(root,'api-keys.json'),'utf8'));assert.deepEqual(disk.keys,{deepseek:'sk-pc-updated-fixture'});await panel.reload();await panel.locator('#key-info').filter({hasText:'未设置'}).waitFor({state:'attached'});
 const good=await readFile(path.join(root,'api-keys.json'));await writeFile(path.join(root,'api-keys.json'),'PRIVATE-CORRUPTED-FILE');await panel.reload();await panel.locator('#pc-key-status').filter({hasText:'PC_FILE_INVALID'}).waitFor({state:'attached'});assert(!(await panel.locator('#pc-key-status').innerText()).includes('PRIVATE-CORRUPTED'));
 await panel.locator('#provider').selectOption('deepseek');await panel.locator('summary').filter({hasText:'设置当前服务的 API key'}).click();await panel.locator('#api-key').fill('sk-pending-fixture');await panel.locator('#save-key').click();await panel.locator('#status').filter({hasText:'尚未写入 PC 文件'}).waitFor();assert.equal(await readFile(path.join(root,'api-keys.json'),'utf8'),'PRIVATE-CORRUPTED-FILE');
 await writeFile(path.join(root,'api-keys.json'),good);await panel.locator('summary').filter({hasText:'PC 文件保存'}).click();await panel.locator('#connect-pc-keys').click();await panel.locator('#status').filter({hasText:'PC 密钥文件已连接'}).waitFor();assert.equal(JSON.parse(await readFile(path.join(root,'api-keys.json'),'utf8')).keys.deepseek,'sk-pending-fixture');
 for(const location of registrations)await rm(location,{force:true});await panel.locator('#clear-key').click();await panel.locator('#status').filter({hasText:'清除未完成'}).waitFor();assert.equal((await worker.evaluate(()=>chrome.storage.local.get('deepseekApiKey'))).deepseekApiKey,'sk-pending-fixture');assert.equal(JSON.parse(await readFile(path.join(root,'api-keys.json'),'utf8')).keys.deepseek,'sk-pending-fixture');
 console.log(JSON.stringify({result:'PASS',platform:process.platform,checks:['real Chrome native messaging','auto migrate both cached keys into separate PC file','fresh browser profile restores both keys','clear one provider without resurrection or deleting the other','corrupted PC file preserved','browser-only failure accurately shown','pending save syncs after repair','offline clear cannot pretend durable deletion','no real credentials or production key path used']}));
}finally{if(ctx)await ctx.close();for(const location of registrations)await rm(location,{force:true});await rm(root,{recursive:true,force:true});}
