import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html=`<!doctype html><meta charset="utf-8"><title>经历新增测试</title><section><h2>实习经历</h2><div id="records"><div class="form"><div class="form-item"><label class="form-item__text">单位名称</label><input value="示例甲"></div></div></div><button id="add" type="button">＋ 添加实习经历</button></section><button id="submit">提交申请</button><script>window.adds=0;window.submits=0;document.querySelector('#add').onclick=()=>{adds++;const c=document.querySelector('.form').cloneNode(true);c.querySelector('input').value='';document.querySelector('#records').append(c)};document.querySelector('#submit').onclick=()=>submits++;</script>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const root=await mkdtemp(path.join(tmpdir(),'resume-add-'));const extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));let ctx,calls=0;
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:process.env.BROWSER_CHANNEL||'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
 await ctx.route('https://api.deepseek.com/chat/completions',async route=>{calls++;const input=JSON.parse(route.request().postDataJSON().messages.at(-1).content);assert.equal(input.fields.length,1);assert(input.fields[0].context.includes('第 2 条'));const passage=input.passages.find(p=>p.category==='internship'&&p.record===2&&p.text==='示例乙');assert(passage);await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills:[{fieldId:input.fields[0].id,passageId:passage.id}]})}}]}});});
 await ctx.route('https://api.typesafe.ai/v1/systemone',async route=>{const body=route.request().postDataJSON(),answers={};body.state.items.forEach((_,i)=>{answers[`q${i}_policy`]={type:'choice',choice:'fact',confidence:.99,probabilities:{fact:.99,passage:.01}};for(const k of ['fit','unsupported','conflict'])answers[`q${i}_${k}`]={type:'noul',noul:k==='fit'?.99:.01};});await route.fulfill({json:{answers}});});
 let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_fixture',deepseekApiKey:'sk-fixture',profile:{base:{},education:[],work:[],custom:[],notes:'实习经历：\n公司：示例甲\n公司：示例乙'}}));
 const target=await ctx.newPage();await target.goto(origin);const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#team-keys').filter({hasText:'Jev：已配置'}).waitFor();await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成'}).waitFor();assert((await panel.locator('#status').innerText()).includes('已自动新增 1 组经历'));assert.deepEqual(await target.locator('.form input').evaluateAll(es=>es.map(e=>e.value)),['示例甲','示例乙']);assert.equal(await target.evaluate(()=>adds),1);assert.equal(calls,1);
 await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 0 项'}).waitFor();assert.equal(await target.evaluate(()=>adds),1);assert.equal(await target.evaluate(()=>submits),0);assert.equal(calls,1);
 console.log(JSON.stringify({result:'PASS',browser:process.env.BROWSER_CHANNEL||'chromium',checks:['one-click panel adds missing internship','background validates scoped add','rescan finds second record','original populated record preserved','new field filled through both mocked providers','second run never duplicates','never submits']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
