import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html=`<!doctype html><meta charset="utf-8"><fieldset><legend>其他信息</legend><div class="form-item"><label class="form-item__text">研究领域</label><div class="ant-select" role="combobox" aria-controls="menu"><span class="ant-select-selection-item"></span><input></div></div></fieldset><div class="ant-select-dropdown" id="menu" role="listbox" style="display:none"><div class="ant-select-item-option" role="option">机器学习</div><div class="ant-select-item-option" role="option">计算机视觉</div></div><button id="save" type="button">保存</button><script>window.saved=0;window.fail=false;save.onclick=()=>saved++;const box=document.querySelector('.ant-select');box.onclick=()=>{if(!window.fail)menu.style.display=menu.style.display==='none'?'block':'none'};box.querySelector('input').onkeydown=e=>{if(e.key==='Escape')menu.style.display='none'};document.querySelectorAll('[role=option]').forEach(n=>n.onclick=()=>{box.querySelector('span').textContent=n.textContent;menu.style.display='none'});</script>`;
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,root=await mkdtemp(path.join(tmpdir(),'resume-operation-retry-')),extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));let ctx,target,calls=0;
try{
 ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
 await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_retry_fixture',deepseekApiKey:'sk-retry-fixture',profile:{base:{},notes:'研究方向：机器学习',education:[],work:[],custom:[]}}));
 await ctx.route('https://api.typesafe.ai/**',async route=>{calls++;const p=route.request().postDataJSON();assert.equal(p.state.stage,'route');const choice=p.state.ranges.find(r=>r.sourceId==='notes').id;await target.evaluate(()=>window.fail=true);await route.fulfill({json:{answers:{q0:{type:'choice',choice,confidence:1,probabilities:{[choice]:1}}}}})});
 await ctx.route('https://api.deepseek.com/**',async route=>{calls++;const p=JSON.parse(route.request().postDataJSON().messages.at(-1).content);await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills:[{fieldId:p.fields[0].id,rangeId:p.assignments[0].range.id,quote:'机器学习',value:'机器学习'}]})}}]}})});
 target=await ctx.newPage();await target.goto(origin);const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#team-keys').filter({hasText:'Jev：已配置'}).waitFor();await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'填写失败 1 项'}).waitFor();assert.equal(calls,2);const retry=panel.getByRole('button',{name:'研究领域 重试该建议',exact:true});await retry.waitFor();assert.equal(await target.locator('.ant-select-selection-item').innerText(),'');
 await target.evaluate(()=>window.fail=false);await target.bringToFront();await retry.click();await panel.locator('#status').filter({hasText:'已重试填入并核验'}).waitFor();assert.equal(await target.locator('.ant-select-selection-item').innerText(),'机器学习');assert.equal(calls,2,'operation retry must not call either model');assert.equal(await panel.locator('.needs-confirmation').count(),1);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts,undefined);assert.equal(await retry.count(),0);
 await target.locator('.ant-select-selection-item').evaluate(e=>e.textContent='');await retry.waitFor();await worker.evaluate(()=>chrome.storage.local.set({profile:{base:{},notes:'研究方向：计算机视觉',education:[],work:[],custom:[]}}));await target.bringToFront();await retry.click();await panel.locator('#status').filter({hasText:'素材或反馈已变化'}).waitFor();assert.equal(await target.locator('.ant-select-selection-item').innerText(),'');assert.equal(calls,2);assert.equal(await target.evaluate(()=>saved),0);
 console.log(JSON.stringify({result:'PASS',checks:['correct proposal with genuine popup failure','single-field operation retry with zero new model calls','fresh value compare-and-set and readback','retry stays orange without implicit learning','late clear remains retryable','changed source blocks stale retry','no website save']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
