import {chromium} from 'playwright';import {createServer} from 'node:http';import {mkdtemp,cp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const html='<!doctype html><meta charset="utf-8"><form><label>姓名<input name="name" value="示例同学"></label><label>研究方向<input name="research" value="旧方向"></label><label>研究领域<select name="area"><option value="-1">请选择</option><option value="ml">机器学习</option></select></label><label>个人技能<input name="skills"></label><label>期望薪资<input name="salary" value="面议"></label><button>保存</button></form><script>window.submits=0;document.querySelector("form").onsubmit=e=>{e.preventDefault();submits++}</script>';
const server=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,root=await mkdtemp(path.join(tmpdir(),'resume-review-existing-')),extension=path.join(root,'extension');await cp('dist',extension,{recursive:true});const manifest=JSON.parse(await readFile(path.join(extension,'manifest.json'),'utf8'));manifest.host_permissions.push(origin+'/*');await writeFile(path.join(extension,'manifest.json'),JSON.stringify(manifest));const routed=[];let ctx,target,race=false,answer="机器学习";
try{ctx=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});let [worker]=ctx.serviceWorkers();if(!worker)worker=await ctx.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
await worker.evaluate(()=>chrome.storage.local.set({apiKey:'apikey_existing_fixture',deepseekApiKey:'sk-existing-fixture',profile:{base:{fullName:'示例同学'},notes:'研究方向：机器学习',education:[],work:[],custom:[]}}));
await ctx.route('https://api.typesafe.ai/**',async route=>{const p=route.request().postDataJSON();assert.equal(p.state.fields.length,1);const label=p.state.fields[0].label;routed.push(label);if(!race&&answer==='机器学习'&&label==='个人技能')assert.equal(await target.locator('[name=research]').inputValue(),'机器学习');if(race&&p.state.fields.some(f=>f.label==='研究方向')){race=false;await target.locator('[name=research]').fill('用户刚刚修改');}const answers={};p.state.fields.forEach((f,i)=>{const choice=f.label==='期望薪资'?'none':p.state.ranges.find(x=>x.sourceId==='notes').id;answers['q'+i]={type:'choice',choice,confidence:1,probabilities:{[choice]:1}}});await route.fulfill({json:{answers}})});
await ctx.route('https://api.deepseek.com/**',async route=>{const p=JSON.parse(route.request().postDataJSON().messages.at(-1).content);await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify({fills:p.fields.map(f=>({fieldId:f.id,rangeId:p.assignments.find(x=>x.fieldId===f.id).range.id,value:f.options?.find(o=>o.label===answer)?.value||answer,quote:answer}))})}}]}})});
target=await ctx.newPage();await target.goto(origin);const panel=await ctx.newPage();await panel.goto(`chrome-extension://${id}/panel.html`);await panel.locator('#team-keys').filter({hasText:'DeepSeek：已配置'}).waitFor();assert(await panel.locator('#review-existing').isChecked());assert(!await panel.locator('#overwrite').isChecked());await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'协作完成：已填入并核验 3 项'}).waitFor();assert.match(await panel.locator('#status').innerText(),/核对一致 1 项/);assert.equal(await target.locator('[name=research]').inputValue(),'机器学习');assert.equal(await target.locator('[name=name]').inputValue(),'示例同学');assert.equal(await target.locator('[name=salary]').inputValue(),'面议');assert.equal(await panel.locator('.needs-confirmation').count(),4);assert.equal((await worker.evaluate(()=>chrome.storage.local.get('learnedFacts'))).learnedFacts,undefined);assert.equal(await target.evaluate(()=>submits),0);
assert.deepEqual(routed,['研究方向','研究领域','个人技能','期望薪资']);assert.equal(await target.locator('[name=area]').inputValue(),'ml');assert.equal(await target.locator('[name=skills]').inputValue(),'机器学习');
await worker.evaluate(()=>chrome.storage.local.set({profile:{base:{fullName:'示例同学'},notes:'研究方向：深度学习',education:[],work:[],custom:[]}}));answer='深度学习';race=true;await target.bringToFront();await panel.locator('#collaborate').click();await panel.locator('#status').filter({hasText:'填写失败 1 项'}).waitFor();assert.equal(await target.locator('[name=research]').inputValue(),'用户刚刚修改');assert.match(await panel.locator('#fields').innerText(),/REVIEW_CHANGED/);
console.log(JSON.stringify({result:'PASS',checks:['mixed controls processed in page order; earlier writes visible before next model request','nonempty native placeholder filled with raw-value race guard','default checks existing filled controls','corrects grounded differences despite manual overwrite being off','matching content counted separately','no-source value retained and warned','analysis-time user edit protected through background bridge','no implicit learning or website save']}));
}finally{if(ctx)await ctx.close();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
